/*
ts:2019-02-08 12:17:00
*/

DELETE FROM `plugin_reports_parameters` WHERE (`report_id` in (select id from plugin_reports_reports where name = 'Student details and bookings doc'));
INSERT INTO `plugin_reports_parameters` (`report_id`, `type`, `name`, `value`, `is_multiselect`) VALUES ((select id from plugin_reports_reports where name = 'Student details and bookings doc'), 'date', 'date', NULL, '0');
INSERT INTO `plugin_reports_parameters` (`report_id`, `type`, `name`, `value`, `is_multiselect`) VALUES ((select id from plugin_reports_reports where name = 'Student details and bookings doc'), 'custom', 'location', 'SELECT \r\n		DISTINCT buildings.id, \r\n		buildings.`name` AS `name`\r\n	FROM plugin_courses_schedules s\r\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id AND e.`delete` = 0 AND s.`delete` = 0\r\n		INNER JOIN plugin_ib_educate_booking_items i ON e.id = i.period_id AND i.`delete` = 0\r\n		INNER JOIN plugin_ib_educate_bookings b ON i.booking_id = b.booking_id AND b.`delete` = 0\r\n		INNER JOIN plugin_courses_courses c ON s.course_id = c.id\r\n		INNER JOIN plugin_courses_locations  locations ON s.location_id = locations.id\r\n		INNER JOIN plugin_courses_locations buildings ON locations.parent_id = buildings.id\r\n	GROUP BY s.id\r\n	ORDER BY buildings.`name`, locations.`name`', '0');
INSERT INTO `plugin_reports_parameters` (`report_id`, `type`, `name`, `value`, `is_multiselect`) VALUES ((select id from plugin_reports_reports where name = 'Student details and bookings doc'), 'custom', 'trainer_id', 'SELECT DISTINCT t.id, CONCAT_WS(\' \', t.title, ifnull(t.first_name, \'No Trainer\'), t.last_name)\r\n	FROM plugin_courses_schedules s\r\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id AND s.delete=0 AND e.delete=0\r\n		LEFT JOIN plugin_contacts3_contacts t ON t.id = IF(e.trainer_id > 0, e.trainer_id, s.trainer_id)\r\n		LEFT JOIN plugin_courses_locations  locations ON s.location_id = locations.id\r\n		LEFT JOIN plugin_courses_locations buildings ON locations.parent_id = buildings.id\r\n	WHERE e.datetime_start >= \'{!date!}\' AND e.datetime_start < DATE_ADD(\'{!date!}\',INTERVAL 1 DAY) AND (buildings.id = \'{!location!}\' or buildings.id is null)\r\n	ORDER BY t.first_name, t.last_name\r\n', '0');
INSERT INTO `plugin_reports_parameters` (`report_id`, `type`, `name`, `value`, `is_multiselect`) VALUES ((select id from plugin_reports_reports where name = 'Student details and bookings doc'), 'custom', 'schedule_id', '(SELECT \r\n		DISTINCT s.id, \r\n		CONCAT( s.`name`, \' \', IF(s.payment_type = 1, \'PrePAY\', \'PAYG\')) AS `name`\r\n	FROM plugin_courses_schedules s\r\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id AND e.`delete` = 0 AND s.`delete` = 0\r\n		INNER JOIN plugin_ib_educate_booking_items i ON e.id = i.period_id AND i.`delete` = 0\r\n		INNER JOIN plugin_ib_educate_bookings b ON i.booking_id = b.booking_id AND b.`delete` = 0\r\n		INNER JOIN plugin_courses_courses c ON s.course_id = c.id\r\n		LEFT JOIN plugin_courses_locations  locations ON s.location_id = locations.id\r\n		LEFT JOIN plugin_courses_locations buildings ON locations.parent_id = buildings.id\r\n	WHERE e.datetime_start >= \'{!date!}\' AND e.datetime_start < DATE_ADD(\'{!date!}\',INTERVAL 1 DAY) AND (s.trainer_id = \'{!trainer_id!}\' OR e.trainer_id = \'{!trainer_id!}\')\r\n	GROUP BY s.id\r\n	ORDER BY buildings.`name`, locations.`name`, s.`name`)', '0');
INSERT INTO `plugin_reports_parameters` (`report_id`, `type`, `name`, `value`, `is_multiselect`) VALUES ((select id from plugin_reports_reports where name = 'Student details and bookings doc'), 'custom', 'timeslot_id', '(SELECT DISTINCT e.id, date_format(e.datetime_start, \'%H:%i\') as timeslot\r\n	FROM plugin_courses_schedules s\r\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id\r\n		WHERE e.datetime_start >= \'{!date!}\' AND e.datetime_start < DATE_ADD(\'{!date!}\',INTERVAL 1 DAY) AND s.id = \'{!schedule_id!}\' AND e.delete=0\r\n	ORDER BY e.datetime_start)', '0');

UPDATE `plugin_reports_reports` SET `sql`='select b.booking_id, b.contact_id as `student_id` , concat_ws(\' \', c.first_name, c.last_name) as `student`\r\n	from plugin_ib_educate_bookings b \r\n		inner join plugin_contacts3_contacts c on b.contact_id = c.id\r\n		inner join plugin_ib_educate_booking_items i on b.booking_id = i.booking_id\r\n	where i.delete = 0 and i.booking_status <> 3 and i.period_id = \'{!timeslot_id!}\'\r\n	order by student' WHERE name = 'Student details and bookings doc';
