/*
ts:2016-11-11 15:22:00
*/

insert into `plugin_reports_reports` set `name` = 'Payment Due',
`summary` = '',
`sql` = 'SELECT\n	t.id AS `Transaction Id`,\n	t4.type AS `Transaction Type`,\n	b.booking_id AS `Booking Id`,\n	CONCAT(c3.first_name, \' \', c3.last_name) AS `Booking Name`,\n	emails.`value` AS `Email`,\n	mobiles.`value` AS `Mobile`,\n	CONCAT(c.title,\' \',c.first_name,\' \',c.last_name) AS `Payee`,\n	s.`name` AS `Schedule`,\n	t.payment_due_date AS `Due Date`,\n	t.amount AS `Amount`,\n	(SELECT\n					IFNULL(SUM(IF(t2.credit, t1.amount, -t1.amount)), 0)\n				FROM\n					plugin_bookings_transactions_payments AS `t1`\n					JOIN plugin_bookings_transactions_payments_statuses AS `t2` ON t1.`status` = t2.id\n				WHERE\n			t1.transaction_id = t.id) AS `Paid`,\n	(t.amount - \n		IFNULL(\n			(SELECT\n					SUM(IF(t2.credit, t1.amount, -t1.amount))\n				FROM\n					plugin_bookings_transactions_payments AS `t1`\n					JOIN plugin_bookings_transactions_payments_statuses AS `t2` ON t1.`status` = t2.id\n				WHERE\n			t1.transaction_id = t.id),\n			0\n		)) AS `Amount Due`\n	\nFROM plugin_bookings_transactions `t`\n	INNER JOIN plugin_bookings_transactions_types `t4` ON t4.id = t.type\n	INNER JOIN plugin_ib_educate_bookings `b` ON t.booking_id = b.booking_id\n	INNER JOIN plugin_contacts3_contacts `c` ON t.contact_id = c.id\n	INNER JOIN plugin_bookings_transactions_has_schedule ts ON t.id = ts.transaction_id AND ts.deleted = 0\n	INNER JOIN plugin_ib_educate_booking_has_schedules bs ON b.booking_id = bs.booking_id AND bs.schedule_id = ts.schedule_id AND bs.deleted = 0\n	INNER JOIN plugin_courses_schedules s ON bs.schedule_id = s.id AND s.`delete` = 0\n	INNER JOIN plugin_courses_courses `c2` ON s.course_id = c2.id\n	INNER JOIN plugin_contacts3_contacts `c3` ON c3.id = b.contact_id\n	LEFT JOIN plugin_contacts3_contact_has_notifications emails ON c3.notifications_group_id = emails.group_id AND emails.notification_id = 1\n	LEFT JOIN plugin_contacts3_contact_has_notifications mobiles ON c3.notifications_group_id = mobiles.group_id AND mobiles.notification_id = 2\n\nWHERE\nt.payment_due_date >= \'{!From!}\' AND t.payment_due_date < DATE_ADD(\'{!To!}\', INTERVAL 1 DAY)\n\nGROUP BY t.id\n\nHAVING `Amount Due` > 0',
`widget_sql` = '',
`category` = '0',
`sub_category` = '0',
`dashboard` = '0',
`created_by` = null,
`modified_by` = null,
`date_created` = NOW(),
`date_modified` = NOW(),
`publish` = '1',
`delete` = '0',
`widget_id` = null,
`chart_id` = null,
`link_url` = '',
`link_column` = '',
`report_type` = 'sql',
`autoload` = '0',
`checkbox_column` = '0',
`action_button_label` = '',
`action_button` = '0',
`action_event` = '',
`checkbox_column_label` = '',
`autosum` = '0',
`column_value` = '',
`autocheck` = '0',
`custom_report_rules` = '',
`bulk_message_sms_number_column` = '',
`bulk_message_email_column` = '',
`bulk_message_subject_column` = '',
`bulk_message_subject` = '',
`bulk_message_body_column` = '',
`bulk_message_body` = '',
`bulk_message_interval` = '',
`rolledback_to_version` = null,
`php_modifier` = '',
`generate_documents` = '0',
`generate_documents_template_file_id` = '0',
`generate_documents_pdf` = '0',
`generate_documents_office_print` = '0',
`generate_documents_office_print_bulk` = '0',
`generate_documents_tray` = null,
`generate_documents_helper_method` = '',
`generate_documents_link_to_contact` = '';
	select last_insert_id() into @refid_plugin_reports_reports_20161111172217_001;
	insert into `plugin_reports_parameters` set `report_id` = @refid_plugin_reports_reports_20161111172217_001,
`type` = 'date',
`name` = 'From',
`value` = '',
`delete` = '0',
`is_multiselect` = '0';
	insert into `plugin_reports_parameters` set `report_id` = @refid_plugin_reports_reports_20161111172217_001,
`type` = 'date',
`name` = 'To',
`value` = '',
`delete` = '0',
`is_multiselect` = '0';

