/*
ts:2016-03-25 14:15:00
*/

UPDATE `plugin_reports_reports`
  SET `sql` = 'SELECT\nt.id AS `Transaction Id`,\nt4.type AS `Transaction Type`,\nb.booking_id AS `Booking Id`,\nCONCAT(c3.first_name, \' \', c3.last_name) AS `Booking Name`,\nt.payment_due_date AS `Due Date`,\n(t.amount - COALESCE(\n(\nSELECT\nSUM(t1.amount)\nFROM\nplugin_bookings_transactions_payments AS `t1`\nJOIN plugin_bookings_transactions_payments_statuses AS `t2` ON t1.`status` = t2.id\nWHERE\nt1.transaction_id = t.id\n),\n0\n)) AS `Amount Due`,\ns.`name` AS `Schedule`,\nCONCAT(c.title,\' \',c.first_name,\' \',c.last_name) AS `Payee`\nFROM plugin_bookings_transactions `t`\n	INNER JOIN plugin_bookings_transactions_types `t4` ON t4.id = t.type\n	INNER JOIN plugin_ib_educate_bookings `b` ON t.booking_id = b.booking_id\n	INNER JOIN plugin_contacts3_contacts `c` ON t.contact_id = c.id\n	INNER JOIN plugin_bookings_transactions_has_schedule ts ON t.id = ts.transaction_id AND ts.deleted = 0\n	INNER JOIN plugin_ib_educate_booking_has_schedules bs ON b.booking_id = bs.booking_id AND bs.schedule_id = ts.schedule_id AND bs.deleted = 0\n	INNER JOIN plugin_courses_schedules s ON bs.schedule_id = s.id AND s.`delete` = 0\n	INNER JOIN plugin_courses_schedules_events `c4` ON s.id = c4.id\n	INNER JOIN plugin_courses_courses `c2` ON s.course_id = c2.id\n	INNER JOIN plugin_contacts3_contacts `c3` ON c3.id = b.contact_id\nWHERE\nt4.type = \'Booking - Pay Now\'\nAND t.payment_due_date >= \'{!From!}\'\nAND t.payment_due_date < DATE_ADD(\'{!To!}\', INTERVAL 1 DAY)\nHAVING\n`Amount Due` > 0'
  WHERE `name` = 'Outstanding Transactions - Prepay'  AND `delete` = 0;

UPDATE `plugin_reports_reports`
  SET `sql` = 'SELECT\nt.id AS `Transaction Id`,\nt4.type AS `Transaction Type`,\nb.booking_id AS `Booking Id`,\nCONCAT(c3.first_name, \' \', c3.last_name) AS `Booking Name`,\nt.payment_due_date AS `Due Date`,\n(t.amount - COALESCE(\n(\nSELECT\nSUM(t1.amount)\nFROM\nplugin_bookings_transactions_payments AS `t1`\nJOIN plugin_bookings_transactions_payments_statuses AS `t2` ON t1.`status` = t2.id\nWHERE\nt1.transaction_id = t.id\n),\n0\n)) AS `Amount Due`,\ns.`name` AS `Schedule`,\nCONCAT(c.title,\' \',c.first_name,\' \',c.last_name) AS `Payee`\nFROM plugin_bookings_transactions `t`\n	INNER JOIN plugin_bookings_transactions_types `t4` ON t4.id = t.type\n	INNER JOIN plugin_ib_educate_bookings `b` ON t.booking_id = b.booking_id\n	INNER JOIN plugin_contacts3_contacts `c` ON t.contact_id = c.id\n	INNER JOIN plugin_bookings_transactions_has_schedule ts ON t.id = ts.transaction_id AND ts.deleted = 0\n	INNER JOIN plugin_ib_educate_booking_has_schedules bs ON b.booking_id = bs.booking_id AND bs.schedule_id = ts.schedule_id AND bs.deleted = 0\n	INNER JOIN plugin_courses_schedules s ON bs.schedule_id = s.id AND s.`delete` = 0\n	INNER JOIN plugin_courses_schedules_events `c4` ON s.id = c4.id\n	INNER JOIN plugin_courses_courses `c2` ON s.course_id = c2.id\n	INNER JOIN plugin_contacts3_contacts `c3` ON c3.id = b.contact_id\nWHERE\nt4.type = \'Booking - PAYG\'\nAND t.payment_due_date >= \'{!From!}\'\nAND t.payment_due_date < DATE_ADD(\'{!To!}\', INTERVAL 1 DAY)\nHAVING\n`Amount Due` > 0'
  WHERE `name` = 'Oustanding Transactions - PAYG'  AND `delete` = 0;

UPDATE `plugin_reports_reports`
  SET `sql` = 'SELECT\nCONCAT(c.first_name,\' \',c.last_name) AS `Students`\nFROM\n	plugin_contacts3_contacts `c`\nWHERE\n	c.id IN(\n		SELECT DISTINCT\n			b0.contact_id\n		FROM\n			plugin_ib_educate_bookings `b0`\n		HAVING\n			(\n				SELECT\n					COUNT(*)\n				FROM\n					plugin_ib_educate_bookings `b`\n				INNER JOIN plugin_ib_educate_booking_items `b1` ON b.booking_id = b1.booking_id\n				WHERE\n					b1.attending = 1\n				AND b.contact_id = b0.contact_id\n			)> 250\n	)\nAND c.id IN(\n	SELECT DISTINCT\n		b.contact_id\n	FROM plugin_ib_educate_bookings `b`\n		INNER JOIN plugin_ib_educate_booking_has_schedules bs ON b.booking_id = bs.booking_id AND bs.deleted = 0\n		INNER JOIN plugin_courses_schedules s ON bs.schedule_id = s.id AND s.`delete` = 0\n		INNER JOIN plugin_bookings_transactions_has_schedule ts ON s.id = ts.schedule_id AND ts.deleted = 0\n		INNER JOIN plugin_bookings_transactions `t` ON ts.transaction_id = t.id AND t.booking_id = b.booking_id\n		INNER JOIN plugin_bookings_transactions_types `t1` ON t1.id = t.type\n	WHERE\n		s.id IN(\n			SELECT\n				c03.id\n			FROM\n				plugin_courses_categories `c01`\n			INNER JOIN plugin_courses_courses `c02` ON c01.id = c02.category_id\n			INNER JOIN plugin_courses_schedules `c03` ON c02.id = c03.course_id\n			WHERE\n				c01.category = \'August Preparation Course \'\n		)\n	AND t1.type = \'Booking - Pay Now\'\n)'
  WHERE `name` = 'Yearly Prepay'  AND `delete` = 0;

UPDATE `plugin_reports_reports`
  SET `sql` = 'SELECT \nCONCAT(\'<var class=\"schedule_id\">\',s.id,\'</var>\') AS `Schedule Id`, \ns.`name` AS `Schedule`, \ns.rental_fee AS `Schedule Rental Fee`,\nc.id AS `Contact Id`, \nCONCAT_WS(\' \', c.title, c.first_name, c.last_name) AS `Contact`, \nCONCAT(\'<var class=\"trainer_id\">\',tr.id,\'</var>\') AS `Schedule Trainer Id`, \nCONCAT(tr.first_name, \' \', tr.last_name) AS `Schedule Trainer`,\nCONCAT(\'<var class=\"transaction_id\">\',t.id, \'</var>\') AS `Transaction Id`, \ntt.type AS `Transaction Type`, \nt.amount AS `Transaction Amount`,\nCONCAT(\'<var class=\"payment_id\">\',p.id, \'</var>\') AS `Payment Id`, \np.created AS `Payment Created`, \np.type AS `Payment Type`, \np.amount AS `Payment Amount`, \np.bank_fee AS `Payment Bank Fee`, \np.currency AS `Payment Currency`, \nps.`status` AS `Payment Status`,\nsp.settlement_id AS `Settlement Id`\n	FROM plugin_bookings_transactions t\n		INNER JOIN plugin_bookings_transactions_types tt ON t.type = tt.id AND t.deleted = 0 AND tt.type = \'Booking - PAYG\'\n		INNER JOIN plugin_bookings_transactions_payments p ON t.id = p.transaction_id AND p.deleted = 0\n		INNER JOIN plugin_bookings_transactions_payments_statuses ps ON p.status = ps.id AND ps.credit = 1\n		INNER JOIN plugin_bookings_transactions_has_schedule ts ON t.id = ts.transaction_id AND ts.deleted = 0\n		INNER JOIN plugin_ib_educate_bookings b ON t.booking_id = b.booking_id AND p.deleted = 0\n		INNER JOIN plugin_contacts3_contacts c ON b.contact_id = c.id\n		INNER JOIN plugin_ib_educate_booking_has_schedules bs ON b.booking_id = bs.booking_id AND bs.schedule_id = ts.schedule_id AND bs.deleted = 0\n		INNER JOIN plugin_courses_schedules s ON bs.schedule_id = s.id AND s.`delete` = 0\n		LEFT JOIN plugin_contacts3_contacts tr ON s.trainer_id = tr.id\n		LEFT JOIN plugin_bookings_settlements_payments sp ON sp.payment_id = p.id\n\nWHERE p.created >= \'{!month_range_from!}\' AND p.created <= \'{!month_range_to!}\' \nAND p.id NOT IN (SELECT journaled_payment_id FROM plugin_bookings_transactions_payments_journal)\nAND p.id NOT IN (SELECT payment_id FROM plugin_bookings_transactions_payments_journal)'
  WHERE `name` = 'Settlement Pay as You Go' AND `delete` = 0;
