/*
ts:2019-01-24 19:12:00
*/

INSERT INTO `plugin_reports_reports` (`name`, `sql`, `report_type`, `generate_documents`, `generate_documents_template_file_id`, `generate_documents_pdf`, `generate_documents_office_print`, `generate_documents_office_print_bulk`, `generate_documents_tray`, `generate_documents_helper_method`, `generate_documents_link_to_contact`) VALUES ('Student details and bookings doc', 'select b.booking_id, b.contact_id as `student_id` , concat_ws(\' \', c.first_name, c.last_name) as student\r\n	from plugin_ib_educate_bookings b \r\n		inner join plugin_ib_educate_booking_has_schedules bhs on b.booking_id = bhs.booking_id\r\n		inner join plugin_contacts3_contacts c on b.contact_id = c.id\r\n	where bhs.deleted = 0 and bhs.booking_status <> 3 and b.contact_id = \'{!student_id!}\'\r\n	order by b.booking_id desc limit 1', 'sql', '1', (select id from plugin_files_file where `name`='Student_Details_and_Bookings' limit 1), '0', '0', '0', '0', 'Model_Docarrayhelper->student_details_and_bookings', 'student_id');
INSERT INTO `plugin_reports_parameters` (`report_id`, `type`, `name`, `value`) VALUES ((select id from plugin_reports_reports where name='Student details and bookings doc' limit 1), 'custom', 'student_id', '((((select distinct b.contact_id as `student_id` , concat_ws(\' \', c.first_name, c.last_name) as student\r\n	from plugin_ib_educate_bookings b \r\n		inner join plugin_ib_educate_booking_has_schedules bhs on b.booking_id = bhs.booking_id\r\n		inner join plugin_contacts3_contacts c on b.contact_id = c.id\r\n	where bhs.deleted = 0 and bhs.booking_status <> 3\r\n	order by b.booking_id))))');

update plugin_reports_parameters set name = 'schedule', `value`='select distinct s.id, s.`name`\n	from plugin_ib_educate_bookings b \n		inner join plugin_ib_educate_booking_has_schedules bhs on b.booking_id = bhs.booking_id\n		inner join plugin_courses_schedules s on bhs.schedule_id = s.id\n	where bhs.deleted = 0 and bhs.booking_status <> 3\n	order by s.`name`' where name='student_id' and report_id = (select id from plugin_reports_reports where name='Student details and bookings doc' limit 1);
update plugin_reports_reports set `generate_documents_link_by_template_variable`='contact_id', `generate_documents_mode`='ROW', `generate_documents_row_variable`='student_id' where (`name`='Student details and bookings doc');

UPDATE `plugin_reports_reports` SET `sql`='select b.booking_id, b.contact_id as `student_id` , concat_ws(\' \', c.first_name, c.last_name) as student\r\n	from plugin_ib_educate_bookings b \r\n		inner join plugin_ib_educate_booking_has_schedules bhs on b.booking_id = bhs.booking_id\r\n		inner join plugin_contacts3_contacts c on b.contact_id = c.id\r\n	where bhs.deleted = 0 and bhs.booking_status <> 3 and bhs.schedule_id = \'{!schedule!}\'\r\n	order by student' where (`name`='Student details and bookings doc');
