/*
ts:2016-11-20 18:00:00
*/


insert into `plugin_messaging_notification_templates`
  set
    `send_interval` = null,
    `name` = 'rollcall-absent-sms',
    `description` = '',
    `driver` = 'SMS',
    `type_id` = '4',
    `subject` = '',
    `sender` = '',
    `message` = 'Please note that $student_name is absent from $schedule. Kilmartin Educational Services 061-444989',
    `overwrite_cms_message` = '0',
    `page_id` = '0',
    `header` = '',
    `footer` = '',
    `schedule` = null,
    `date_created` = NOW(),
    `created_by` = 1,
    `date_updated` = null,
    `last_sent` = null,
    `publish` = '1',
    `deleted` = '0',
    `create_via_code` = 'Roll Call',
    `usable_parameters_in_template` = '$student_name,$schedule',
    `doc_generate` = null,
    `doc_helper` = null,
    `doc_template_path` = null,
    `doc_type` = null,
    `category_id` = '0';

insert into `plugin_messaging_notification_templates`
  set
    `send_interval` = null,
    `name` = 'rollcall-left-early-sms',
    `description` = '',
    `driver` = 'SMS',
    `type_id` = '4',
    `subject` = '',
    `sender` = '',
    `message` = 'Please note that $student_name left $schedule early today. Kilmartin Educational Services 061-444989',
    `overwrite_cms_message` = '0',
    `page_id` = '0',
    `header` = '',
    `footer` = '',
    `schedule` = null,
    `date_created` = NOW(),
    `created_by` = 1,
    `date_updated` = null,
    `last_sent` = null,
    `publish` = '1',
    `deleted` = '0',
    `create_via_code` = 'Roll Call',
    `usable_parameters_in_template` = '$student_name, $schedule',
    `doc_generate` = null,
    `doc_helper` = null,
    `doc_template_path` = null,
    `doc_type` = null,
    `category_id` = '0';

insert into `plugin_messaging_notification_templates`
  set
    `send_interval` = null,
    `name` = 'rollcall-signed-late-sms',
    `description` = '',
    `driver` = 'SMS',
    `type_id` = '4',
    `subject` = '',
    `sender` = '',
    `message` = 'Please note that $student_name signed into $schedule late today. Kilmartin Educational Services 061-444989',
    `overwrite_cms_message` = '0',
    `page_id` = '0',
    `header` = '',
    `footer` = '',
    `schedule` = null,
    `date_created` = NOW(),
    `created_by` = 1,
    `date_updated` = null,
    `last_sent` = null,
    `publish` = '1',
    `deleted` = '0',
    `create_via_code` = 'Roll Call',
    `usable_parameters_in_template` = '$student_name, $schedule',
    `doc_generate` = null,
    `doc_helper` = null,
    `doc_template_path` = null,
    `doc_type` = null,
    `category_id` = '0';


insert into `plugin_reports_reports`
	set
		`name` = 'Daily Course Reminder Prepay',
		`summary` = '',
		`sql` = 'SELECT\n		CONCAT_WS(\' \',plugin_contacts3_contacts.title, plugin_contacts3_contacts.first_name, plugin_contacts3_contacts.last_name) AS `Student`,\n		CONCAT_WS(\' \',pcontact.title, pcontact.first_name, pcontact.last_name) AS `Parent`,\n		CONCAT_WS(\' \',plugin_courses_schedules.`name`,plugin_courses_courses.title) AS `Schedule`,\n		pcontact_notifications.`value` AS `Mobile`,\n		plugin_courses_schedules_events.`datetime_start` AS `Time`,\n		IF (location.id IS NOT NULL, location.`name`, room.`name`) AS `Location`,\n		plugin_ib_educate_bookings.booking_id AS `Booking Id`,\n		CONCAT_WS(\' \',trainers.title, trainers.first_name, trainers.last_name) AS `Trainer`\n	FROM plugin_ib_educate_booking_items\n		INNER JOIN plugin_ib_educate_bookings ON plugin_ib_educate_booking_items.booking_id = plugin_ib_educate_bookings.booking_id AND plugin_ib_educate_bookings.`delete` = 0 AND plugin_ib_educate_booking_items.`delete` = 0\n		INNER JOIN plugin_courses_schedules_events ON plugin_ib_educate_booking_items.period_id = plugin_courses_schedules_events.id AND plugin_courses_schedules_events.`delete` = 0\n		INNER JOIN plugin_courses_schedules ON plugin_courses_schedules_events.schedule_id = plugin_courses_schedules.id\n		INNER JOIN plugin_courses_courses ON plugin_courses_schedules.course_id = plugin_courses_courses.id\n		INNER JOIN plugin_courses_categories ON plugin_courses_courses.category_id = plugin_courses_categories.id\n		INNER JOIN plugin_contacts3_contacts ON plugin_ib_educate_bookings.contact_id = plugin_contacts3_contacts.id\n		LEFT JOIN plugin_contacts3_contacts trainers ON plugin_courses_schedules_events.trainer_id = trainers.id\n		LEFT JOIN plugin_courses_locations room ON plugin_courses_schedules.location_id = room.id\n		LEFT JOIN plugin_courses_locations location ON room.parent_id = location.id\n		LEFT JOIN plugin_contacts3_family ON plugin_contacts3_contacts.family_id = plugin_contacts3_family.family_id\n		LEFT JOIN plugin_contacts3_contacts pcontact ON plugin_contacts3_family.primary_contact_id = pcontact.id\n		LEFT JOIN plugin_contacts3_contact_has_notifications ON plugin_contacts3_contacts.notifications_group_id = plugin_contacts3_contact_has_notifications.group_id AND plugin_contacts3_contact_has_notifications.notification_id = 2\n		LEFT JOIN plugin_contacts3_contact_has_notifications pcontact_notifications ON pcontact.notifications_group_id = pcontact_notifications.group_id AND pcontact_notifications.notification_id = 2\n	WHERE\n		plugin_courses_schedules_events.datetime_start >= DATE_ADD(CURDATE(), interval 1 day) AND\n		plugin_courses_schedules_events.datetime_start < DATE_ADD(CURDATE(), interval 2 day) AND\n		plugin_ib_educate_bookings.booking_status IN (2, 4) AND\n		plugin_ib_educate_booking_items.booking_status IN (2, 4) AND\n		plugin_courses_schedules.payment_type = 1 AND \n		plugin_courses_categories.category <> \'Supervised Study\'\n	ORDER BY `Student`',
		`widget_sql` = '',
		`category` = '0',
		`sub_category` = '0',
		`dashboard` = '0',
		`created_by` = null,
		`modified_by` = null,
		`date_created` = NOW(),
		`date_modified` = NOW(),
		`publish` = '1',
		`delete` = '0',
		`widget_id` = null,
		`chart_id` = null,
		`link_url` = '',
		`link_column` = '',
		`report_type` = 'sql',
		`autoload` = '0',
		`checkbox_column` = '0',
		`action_button_label` = '',
		`action_button` = '0',
		`action_event` = '',
		`checkbox_column_label` = '',
		`autosum` = '0',
		`column_value` = '',
		`autocheck` = '0',
		`custom_report_rules` = '',
		`bulk_message_sms_number_column` = 'Mobile',
		`bulk_message_email_column` = '',
		`bulk_message_subject_column` = '',
		`bulk_message_subject` = '',
		`bulk_message_body_column` = '',
		`bulk_message_body` = '{Student} is due in for {Schedule} on {Time} with {Trainer} in {Location}. Roll Calls are *15 minutes before start time* sharp. Please note no allowances made for absenteeism. Fees are non-refundable and non-transferable. Kilmartin Educational Services 061-444989',
		`bulk_message_interval` = '0 0 * * *',
		`rolledback_to_version` = null,
		`php_modifier` = '',
		`generate_documents` = '0',
		`generate_documents_template_file_id` = '0',
		`generate_documents_pdf` = '0',
		`generate_documents_office_print` = '0',
		`generate_documents_office_print_bulk` = '0',
		`generate_documents_tray` = null,
		`generate_documents_helper_method` = '',
		`generate_documents_link_to_contact` = '';

insert into `plugin_reports_reports`
	set
		`name` = 'Daily Course Reminder PAYG',
		`summary` = '',
		`sql` = 'SELECT\n		CONCAT_WS(\' \',plugin_contacts3_contacts.title, plugin_contacts3_contacts.first_name, plugin_contacts3_contacts.last_name) AS `Student`,\n		CONCAT_WS(\' \',pcontact.title, pcontact.first_name, pcontact.last_name) AS `Parent`,\n		CONCAT_WS(\' \',plugin_courses_schedules.`name`,plugin_courses_courses.title) AS `Schedule`,\n		pcontact_notifications.`value` AS `Mobile`,\n		plugin_courses_schedules_events.`datetime_start` AS `Time`,\n		IF (location.id IS NOT NULL, location.`name`, room.`name`) AS `Location`,\n		plugin_ib_educate_bookings.booking_id AS `Booking Id`,\n		CONCAT_WS(\' \',trainers.title, trainers.first_name, trainers.last_name) AS `Trainer`\n	FROM plugin_ib_educate_booking_items\n		INNER JOIN plugin_ib_educate_bookings ON plugin_ib_educate_booking_items.booking_id = plugin_ib_educate_bookings.booking_id AND plugin_ib_educate_bookings.`delete` = 0 AND plugin_ib_educate_booking_items.`delete` = 0\n		INNER JOIN plugin_courses_schedules_events ON plugin_ib_educate_booking_items.period_id = plugin_courses_schedules_events.id AND plugin_courses_schedules_events.`delete` = 0\n		INNER JOIN plugin_courses_schedules ON plugin_courses_schedules_events.schedule_id = plugin_courses_schedules.id\n		INNER JOIN plugin_courses_courses ON plugin_courses_schedules.course_id = plugin_courses_courses.id\n		INNER JOIN plugin_courses_categories ON plugin_courses_courses.category_id = plugin_courses_categories.id\n		INNER JOIN plugin_contacts3_contacts ON plugin_ib_educate_bookings.contact_id = plugin_contacts3_contacts.id\n		LEFT JOIN plugin_contacts3_contacts trainers ON plugin_courses_schedules_events.trainer_id = trainers.id\n		LEFT JOIN plugin_courses_locations room ON plugin_courses_schedules.location_id = room.id\n		LEFT JOIN plugin_courses_locations location ON room.parent_id = location.id\n		LEFT JOIN plugin_contacts3_family ON plugin_contacts3_contacts.family_id = plugin_contacts3_family.family_id\n		LEFT JOIN plugin_contacts3_contacts pcontact ON plugin_contacts3_family.primary_contact_id = pcontact.id\n		LEFT JOIN plugin_contacts3_contact_has_notifications ON plugin_contacts3_contacts.notifications_group_id = plugin_contacts3_contact_has_notifications.group_id AND plugin_contacts3_contact_has_notifications.notification_id = 2\n		LEFT JOIN plugin_contacts3_contact_has_notifications pcontact_notifications ON pcontact.notifications_group_id = pcontact_notifications.group_id AND pcontact_notifications.notification_id = 2\n	WHERE\n		plugin_courses_schedules_events.datetime_start >= DATE_ADD(CURDATE(), interval 1 day) AND\n		plugin_courses_schedules_events.datetime_start < DATE_ADD(CURDATE(), interval 2 day) AND\n		plugin_ib_educate_bookings.booking_status IN (2, 4) AND\n		plugin_ib_educate_booking_items.booking_status IN (2, 4) AND\n		plugin_courses_schedules.payment_type = 2 AND \n		plugin_courses_categories.category <> \'Supervised Study\'\n	ORDER BY `Student`',
		`widget_sql` = '',
		`category` = '0',
		`sub_category` = '0',
		`dashboard` = '0',
		`created_by` = null,
		`modified_by` = null,
		`date_created` = NOW(),
		`date_modified` = NOW(),
		`publish` = '1',
		`delete` = '0',
		`widget_id` = null,
		`chart_id` = null,
		`link_url` = '',
		`link_column` = '',
		`report_type` = 'sql',
		`autoload` = '0',
		`checkbox_column` = '0',
		`action_button_label` = '',
		`action_button` = '0',
		`action_event` = '',
		`checkbox_column_label` = '',
		`autosum` = '0',
		`column_value` = '',
		`autocheck` = '0',
		`custom_report_rules` = '',
		`bulk_message_sms_number_column` = 'Mobile',
		`bulk_message_email_column` = '',
		`bulk_message_subject_column` = '',
		`bulk_message_subject` = '',
		`bulk_message_body_column` = '',
		`bulk_message_body` = '{Student} is due in for {Schedule} on {Time} with {Trainer} in {Location}. Roll Calls are *15 minutes before start time* sharp. Kilmartin Educational Services 061-444989 ',
		`bulk_message_interval` = '0 0 * * *',
		`rolledback_to_version` = null,
		`php_modifier` = '',
		`generate_documents` = '0',
		`generate_documents_template_file_id` = '0',
		`generate_documents_pdf` = '0',
		`generate_documents_office_print` = '0',
		`generate_documents_office_print_bulk` = '0',
		`generate_documents_tray` = null,
		`generate_documents_helper_method` = '',
		`generate_documents_link_to_contact` = '';

insert into `plugin_reports_reports`
	set
		`name` = 'Daily Course Reminder Supervised Study',
		`summary` = '',
		`sql` = 'SELECT\n		CONCAT_WS(\' \',plugin_contacts3_contacts.title, plugin_contacts3_contacts.first_name, plugin_contacts3_contacts.last_name) AS `Student`,\n		CONCAT_WS(\' \',pcontact.title, pcontact.first_name, pcontact.last_name) AS `Parent`,\n		CONCAT_WS(\' \',plugin_courses_schedules.`name`,plugin_courses_courses.title) AS `Schedule`,\n		pcontact_notifications.`value` AS `Mobile`,\n		plugin_courses_schedules_events.`datetime_start` AS `Time`,\n		location.`name` AS `Location`, room.`name` AS `Room`,\n		plugin_ib_educate_bookings.booking_id AS `Booking Id`,\n		CONCAT_WS(\' \',trainers.title, trainers.first_name, trainers.last_name) AS `Trainer`\n	FROM plugin_ib_educate_booking_items\n		INNER JOIN plugin_ib_educate_bookings ON plugin_ib_educate_booking_items.booking_id = plugin_ib_educate_bookings.booking_id AND plugin_ib_educate_bookings.`delete` = 0 AND plugin_ib_educate_booking_items.`delete` = 0\n		INNER JOIN plugin_courses_schedules_events ON plugin_ib_educate_booking_items.period_id = plugin_courses_schedules_events.id AND plugin_courses_schedules_events.`delete` = 0\n		INNER JOIN plugin_courses_schedules ON plugin_courses_schedules_events.schedule_id = plugin_courses_schedules.id\n		INNER JOIN plugin_courses_courses ON plugin_courses_schedules.course_id = plugin_courses_courses.id\n		INNER JOIN plugin_courses_categories ON plugin_courses_courses.category_id = plugin_courses_categories.id\n		INNER JOIN plugin_contacts3_contacts ON plugin_ib_educate_bookings.contact_id = plugin_contacts3_contacts.id\n		LEFT JOIN plugin_contacts3_contacts trainers ON plugin_courses_schedules_events.trainer_id = trainers.id\n		LEFT JOIN plugin_courses_locations room ON plugin_courses_schedules.location_id = room.id\n		LEFT JOIN plugin_courses_locations location ON room.parent_id = location.id\n		LEFT JOIN plugin_contacts3_family ON plugin_contacts3_contacts.family_id = plugin_contacts3_family.family_id\n		LEFT JOIN plugin_contacts3_contacts pcontact ON plugin_contacts3_family.primary_contact_id = pcontact.id\n		LEFT JOIN plugin_contacts3_contact_has_notifications ON plugin_contacts3_contacts.notifications_group_id = plugin_contacts3_contact_has_notifications.group_id AND plugin_contacts3_contact_has_notifications.notification_id = 2\n		LEFT JOIN plugin_contacts3_contact_has_notifications pcontact_notifications ON pcontact.notifications_group_id = pcontact_notifications.group_id AND pcontact_notifications.notification_id = 2\n	WHERE\n		plugin_courses_schedules_events.datetime_start >= DATE_ADD(CURDATE(), interval 1 day) AND\n		plugin_courses_schedules_events.datetime_start < DATE_ADD(CURDATE(), interval 2 day) AND\n		plugin_ib_educate_bookings.booking_status IN (2, 4) AND\n		plugin_ib_educate_booking_items.booking_status IN (2, 4) AND\n		plugin_courses_categories.category = \'Supervised Study\'\n	ORDER BY `Student`',
		`widget_sql` = '',
		`category` = '0',
		`sub_category` = '0',
		`dashboard` = '0',
		`created_by` = null,
		`modified_by` = null,
		`date_created` = NOW(),
		`date_modified` = NOW(),
		`publish` = '1',
		`delete` = '0',
		`widget_id` = null,
		`chart_id` = null,
		`link_url` = '',
		`link_column` = '',
		`report_type` = 'sql',
		`autoload` = '0',
		`checkbox_column` = '0',
		`action_button_label` = '',
		`action_button` = '0',
		`action_event` = '',
		`checkbox_column_label` = '',
		`autosum` = '0',
		`column_value` = '',
		`autocheck` = '0',
		`custom_report_rules` = '',
		`bulk_message_sms_number_column` = 'Mobile',
		`bulk_message_email_column` = '',
		`bulk_message_subject_column` = '',
		`bulk_message_subject` = '',
		`bulk_message_body_column` = '',
		`bulk_message_body` = '{Student} is due in for supervised study on {Time} in {Room} in {Location}. Roll Calls are *15 minutes before start time* sharp. Please note no allowances made for absenteeism. Fees are non-refundable and non-transferable. Kilmartin Educational Services 061-444989',
		`bulk_message_interval` = '0 0 * * *',
		`rolledback_to_version` = null,
		`php_modifier` = '',
		`generate_documents` = '0',
		`generate_documents_template_file_id` = '0',
		`generate_documents_pdf` = '0',
		`generate_documents_office_print` = '0',
		`generate_documents_office_print_bulk` = '0',
		`generate_documents_tray` = null,
		`generate_documents_helper_method` = '',
		`generate_documents_link_to_contact` = '';

insert into `plugin_reports_reports`
	set
		`name` = 'Marketing 1',
		`summary` = '',
		`sql` = 'SELECT\n		CONCAT_WS(\' \',students.title, students.first_name, students.last_name) AS `Student`,\n		CONCAT_WS(\' \',pcontact.title, pcontact.first_name, pcontact.last_name) AS `Parent`,\n		pcontact_notifications.`value` AS `Mobile`,\n		CONCAT_WS(\' \', locations.`name`, rooms.`name`) AS `Room`,\n		courses.title AS `Course`,\n		courses.id AS `Course Id`,\n		schedules.`name` AS `Schedule`,\n		schedules.id AS `Schedule Id`,\n		bookings.booking_id AS `Booking ID`,\n		schedules.max_capacity AS `Capacity`,\n		bookings_count AS `Bookings Count`,\n		(schedules.max_capacity - bookings_count) AS `Remaining Capacity`\n	FROM plugin_courses_locations rooms\n		INNER JOIN plugin_courses_locations locations ON rooms.parent_id = locations.id\n		INNER JOIN plugin_courses_schedules schedules ON schedules.location_id = rooms.id\n		INNER JOIN plugin_courses_courses courses ON schedules.course_id = courses.id\n		INNER JOIN plugin_courses_categories categories ON courses.category_id = categories.id\n		INNER JOIN plugin_ib_educate_booking_has_schedules has_schedules ON schedules.id = has_schedules.schedule_id\n		INNER JOIN plugin_ib_educate_bookings bookings ON has_schedules.booking_id = bookings.booking_id\n		INNER JOIN plugin_contacts3_contacts students ON bookings.contact_id = students.id\n		LEFT JOIN plugin_contacts3_family families ON students.family_id = families.family_id\n		LEFT JOIN plugin_contacts3_contacts pcontact ON families.primary_contact_id = pcontact.id\n		LEFT JOIN plugin_contacts3_contact_has_notifications student_mobiles ON students.notifications_group_id = student_mobiles.group_id AND student_mobiles.notification_id = 2\n		LEFT JOIN plugin_contacts3_contact_has_notifications pcontact_notifications ON pcontact.notifications_group_id = pcontact_notifications.group_id AND pcontact_notifications.notification_id = 2\n		INNER JOIN\n		(\n			SELECT\n				rooms.id AS room_id,\n				schedules.id AS schedule_id,\n				COUNT(*) AS bookings_count\n			FROM plugin_courses_locations rooms\n				INNER JOIN plugin_courses_locations locations ON rooms.parent_id = locations.id\n				INNER JOIN plugin_courses_schedules schedules ON schedules.location_id = rooms.id\n				INNER JOIN plugin_ib_educate_booking_has_schedules has_schedules ON schedules.id = has_schedules.schedule_id\n				INNER JOIN plugin_ib_educate_bookings bookings ON has_schedules.booking_id = bookings.booking_id\n			GROUP BY schedules.id\n		) capacities_left ON schedules.id = capacities_left.schedule_id\n	WHERE\n		bookings.`delete` = 0 AND bookings.booking_status IN (2, 4) AND\n		has_schedules.deleted = 0 AND has_schedules.booking_status IN (2, 4) AND\n		schedules.id = {!Schedule Booked!} AND\n		students.id NOT IN (SELECT\n				students.id\n			FROM plugin_courses_locations rooms\n				INNER JOIN plugin_courses_locations locations ON rooms.parent_id = locations.id\n				INNER JOIN plugin_courses_schedules schedules ON schedules.location_id = rooms.id\n				INNER JOIN plugin_courses_courses courses ON schedules.course_id = courses.id\n				INNER JOIN plugin_courses_categories categories ON courses.category_id = categories.id\n				INNER JOIN plugin_ib_educate_booking_has_schedules has_schedules ON schedules.id = has_schedules.schedule_id\n				INNER JOIN plugin_ib_educate_bookings bookings ON has_schedules.booking_id = bookings.booking_id\n				INNER JOIN plugin_contacts3_contacts students ON bookings.contact_id = students.id\n				LEFT JOIN plugin_contacts3_family families ON students.family_id = families.family_id\n				LEFT JOIN plugin_contacts3_contacts pcontact ON families.primary_contact_id = pcontact.id\n				LEFT JOIN plugin_contacts3_contact_has_notifications student_mobiles ON students.notifications_group_id = student_mobiles.group_id AND student_mobiles.notification_id = 2\n				LEFT JOIN plugin_contacts3_contact_has_notifications pcontact_notifications ON pcontact.notifications_group_id = pcontact_notifications.group_id AND pcontact_notifications.notification_id = 2\n			WHERE\n				bookings.`delete` = 0 AND bookings.booking_status IN (2, 4) AND\n				has_schedules.deleted = 0 AND has_schedules.booking_status IN (2, 4) AND\n				schedules.id = {!Schedule Not Booked!}\n			GROUP BY students.id, schedules.id\n		)\n	GROUP BY students.id, schedules.id\n	ORDER BY `Student`',
		`widget_sql` = '',
		`category` = '0',
		`sub_category` = '0',
		`dashboard` = '0',
		`created_by` = null,
		`modified_by` = null,
		`date_created` = NOW(),
		`date_modified` = NOW(),
		`publish` = '1',
		`delete` = '0',
		`widget_id` = null,
		`chart_id` = null,
		`link_url` = '',
		`link_column` = '',
		`report_type` = 'sql',
		`autoload` = '0',
		`checkbox_column` = '0',
		`action_button_label` = '',
		`action_button` = '0',
		`action_event` = '',
		`checkbox_column_label` = '',
		`autosum` = '0',
		`column_value` = '',
		`autocheck` = '0',
		`custom_report_rules` = '',
		`bulk_message_sms_number_column` = 'Mobile',
		`bulk_message_email_column` = '',
		`bulk_message_subject_column` = '',
		`bulk_message_subject` = '',
		`bulk_message_body_column` = '',
		`bulk_message_body` = 'Please note that there are only {Remaining Capacity} places remaining in {Room} for {Schedule}. For bookings, please contact 061-444989. Thank you. Kilmartin Educational Services.',
		`bulk_message_interval` = '',
		`rolledback_to_version` = null,
		`php_modifier` = '',
		`generate_documents` = '0',
		`generate_documents_template_file_id` = '0',
		`generate_documents_pdf` = '0',
		`generate_documents_office_print` = '0',
		`generate_documents_office_print_bulk` = '0',
		`generate_documents_tray` = null,
		`generate_documents_helper_method` = '',
		`generate_documents_link_to_contact` = '';

select last_insert_id() into @refid_plugin_reports_reports_20161120224113_001;

insert into `plugin_reports_parameters`
	set
		`report_id` = @refid_plugin_reports_reports_20161120224113_001,
		`type` = 'custom',
		`name` = 'Schedule Booked',
		`value` = 'SELECT\n		DISTINCT\n		s.id AS `Schedule Id`,\n		CONCAT_WS(\' \', s.`name`, \' \', pl.`name`, l.name) AS `Schedule`\n	FROM plugin_courses_schedules s\n		INNER JOIN plugin_courses_courses c ON s.course_id = c.id\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id\n		LEFT JOIN plugin_courses_locations l ON s.location_id = l.id\n		LEFT JOIN plugin_courses_locations pl ON l.parent_id = pl.id\n	WHERE \n		s.`delete` = 0 AND c.deleted = 0 AND e.`delete` = 0 AND \n		e.datetime_start >= NOW() \n	ORDER BY s.`name`',
		`delete` = '0',
		`is_multiselect` = '0';

insert into `plugin_reports_parameters`
	set
		`report_id` = @refid_plugin_reports_reports_20161120224113_001,
		`type` = 'custom',
		`name` = 'Schedule Not Booked',
		`value` = 'SELECT\n		DISTINCT\n		s.id AS `Schedule Id`,\n		CONCAT_WS(\' \', s.`name`, \' \', pl.`name`, l.name) AS `Schedule`\n	FROM plugin_courses_schedules s\n		INNER JOIN plugin_courses_courses c ON s.course_id = c.id\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id\n		LEFT JOIN plugin_courses_locations l ON s.location_id = l.id\n		LEFT JOIN plugin_courses_locations pl ON l.parent_id = pl.id\n	WHERE \n		s.`delete` = 0 AND c.deleted = 0 AND e.`delete` = 0 AND \n		e.datetime_start >= NOW() \n	ORDER BY s.`name`',
		`delete` = '0',
		`is_multiselect` = '0';

insert into `plugin_reports_reports`
	set
		`name` = 'Marketing 2',
		`summary` = '',
		`sql` = 'SELECT\n		CONCAT_WS(\' \',students.title, students.first_name, students.last_name) AS `Student`,\n		CONCAT_WS(\' \',pcontact.title, pcontact.first_name, pcontact.last_name) AS `Parent`,\n		pcontact_notifications.`value` AS `Mobile`,\n		CONCAT_WS(\' \', locations.`name`, rooms.`name`) AS `Room`,\n		courses.title AS `Course`,\n		courses.id AS `Course Id`,\n		schedules.`name` AS `Schedule`,\n		schedules.id AS `Schedule Id`,\n		bookings.booking_id AS `Booking ID`\n	FROM plugin_courses_locations rooms\n		INNER JOIN plugin_courses_locations locations ON rooms.parent_id = locations.id\n		INNER JOIN plugin_courses_schedules schedules ON schedules.location_id = rooms.id\n		INNER JOIN plugin_courses_courses courses ON schedules.course_id = courses.id\n		INNER JOIN plugin_courses_categories categories ON courses.category_id = categories.id\n		INNER JOIN plugin_ib_educate_booking_has_schedules has_schedules ON schedules.id = has_schedules.schedule_id\n		INNER JOIN plugin_ib_educate_bookings bookings ON has_schedules.booking_id = bookings.booking_id\n		INNER JOIN plugin_contacts3_contacts students ON bookings.contact_id = students.id\n		LEFT JOIN plugin_contacts3_family families ON students.family_id = families.family_id\n		LEFT JOIN plugin_contacts3_contacts pcontact ON families.primary_contact_id = pcontact.id\n		LEFT JOIN plugin_contacts3_contact_has_notifications student_mobiles ON students.notifications_group_id = student_mobiles.group_id AND student_mobiles.notification_id = 2\n		LEFT JOIN plugin_contacts3_contact_has_notifications pcontact_notifications ON pcontact.notifications_group_id = pcontact_notifications.group_id AND pcontact_notifications.notification_id = 2\n	WHERE\n		bookings.`delete` = 0 AND bookings.booking_status IN (2, 4) AND\n		has_schedules.deleted = 0 AND has_schedules.booking_status IN (2, 4) AND\n		courses.id IN ({!Course Booked!}) AND\n		students.id NOT IN (SELECT\n				students.id\n			FROM plugin_courses_locations rooms\n				INNER JOIN plugin_courses_locations locations ON rooms.parent_id = locations.id\n				INNER JOIN plugin_courses_schedules schedules ON schedules.location_id = rooms.id\n				INNER JOIN plugin_courses_courses courses ON schedules.course_id = courses.id\n				INNER JOIN plugin_courses_categories categories ON courses.category_id = categories.id\n				INNER JOIN plugin_ib_educate_booking_has_schedules has_schedules ON schedules.id = has_schedules.schedule_id\n				INNER JOIN plugin_ib_educate_bookings bookings ON has_schedules.booking_id = bookings.booking_id\n				INNER JOIN plugin_contacts3_contacts students ON bookings.contact_id = students.id\n				LEFT JOIN plugin_contacts3_family families ON students.family_id = families.family_id\n				LEFT JOIN plugin_contacts3_contacts pcontact ON families.primary_contact_id = pcontact.id\n				LEFT JOIN plugin_contacts3_contact_has_notifications student_mobiles ON students.notifications_group_id = student_mobiles.group_id AND student_mobiles.notification_id = 2\n				LEFT JOIN plugin_contacts3_contact_has_notifications pcontact_notifications ON pcontact.notifications_group_id = pcontact_notifications.group_id AND pcontact_notifications.notification_id = 2\n			WHERE\n				bookings.`delete` = 0 AND bookings.booking_status IN (2, 4) AND\n				has_schedules.deleted = 0 AND has_schedules.booking_status IN (2, 4) AND\n				courses.id IN ({!Course Not Booked!})\n			GROUP BY students.id, schedules.id\n		)\n	GROUP BY students.id, schedules.id\n	ORDER BY `Student`',
		`widget_sql` = '',
		`category` = '0',
		`sub_category` = '0',
		`dashboard` = '0',
		`created_by` = null,
		`modified_by` = null,
		`date_created` = NOW(),
		`date_modified` = NOW(),
		`publish` = '1',
		`delete` = '0',
		`widget_id` = NULL,
		`chart_id` = NULL,
		`link_url` = '',
		`link_column` = '',
		`report_type` = 'sql',
		`autoload` = '0',
		`checkbox_column` = '0',
		`action_button_label` = '',
		`action_button` = '0',
		`action_event` = '',
		`checkbox_column_label` = '',
		`autosum` = '0',
		`column_value` = '',
		`autocheck` = '0',
		`custom_report_rules` = '',
		`bulk_message_sms_number_column` = 'Mobile',
		`bulk_message_email_column` = '',
		`bulk_message_subject_column` = '',
		`bulk_message_subject` = '',
		`bulk_message_body_column` = '',
		`bulk_message_body` = 'Please note that the half price offer for booking Easter Revision Courses expires on 31st January. Call 061-444989 to book. Thank you. Kilmartin Educational Services',
		`bulk_message_interval` = '',
		`rolledback_to_version` = null,
		`php_modifier` = '',
		`generate_documents` = '0',
		`generate_documents_template_file_id` = '0',
		`generate_documents_pdf` = '0',
		`generate_documents_office_print` = '0',
		`generate_documents_office_print_bulk` = '0',
		`generate_documents_tray` = null,
		`generate_documents_helper_method` = '',
		`generate_documents_link_to_contact` = '';

select last_insert_id() into @refid_plugin_reports_reports_20161120225614_001;

insert into `plugin_reports_parameters`
	set
		`report_id` = @refid_plugin_reports_reports_20161120225614_001,
		`type` = 'custom',
		`name` = 'Course Booked',
		`value` = '((((SELECT\n		DISTINCT\n		c.id AS `Course Id`,\n		c.title AS `Course` \n		\n	FROM plugin_courses_schedules s\n		INNER JOIN plugin_courses_courses c ON s.course_id = c.id\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id\n	WHERE \n		s.`delete` = 0 AND c.deleted = 0 AND e.`delete` = 0 AND \n		e.datetime_start >= NOW()\n	ORDER BY c.title))))',
		`delete` = '0',
		`is_multiselect` = '0';

insert into `plugin_reports_parameters`
	set
		`report_id` = @refid_plugin_reports_reports_20161120225614_001,
		`type` = 'custom',
		`name` = 'Course Not Booked',
		`value` = '((((SELECT\n		DISTINCT\n		c.id AS `Course Id`,\n		c.title AS `Course` \n		\n	FROM plugin_courses_schedules s\n		INNER JOIN plugin_courses_courses c ON s.course_id = c.id\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id\n	WHERE \n		s.`delete` = 0 AND c.deleted = 0 AND e.`delete` = 0 AND \n		e.datetime_start >= NOW()\n	ORDER BY c.title))))',
		`delete` = '0',
		`is_multiselect` = '0';

insert into `plugin_reports_reports`
	set
		`name` = 'Marketing 3',
		`summary` = '',
		`sql` = 'SELECT\n		CONCAT_WS(\' \', students.title, students.first_name, students.last_name) AS `Student`,\n		CONCAT_WS(\' \',pcontact.title, pcontact.first_name, pcontact.last_name) AS `Parent`,\n		pcontact_notifications.`value` AS `Mobile`\n	FROM plugin_courses_locations rooms\n		INNER JOIN plugin_courses_locations locations ON rooms.parent_id = locations.id\n		INNER JOIN plugin_courses_schedules schedules ON schedules.location_id = rooms.id\n		INNER JOIN plugin_courses_courses courses ON schedules.course_id = courses.id\n		INNER JOIN plugin_courses_categories categories ON courses.category_id = categories.id\n		INNER JOIN plugin_ib_educate_booking_has_schedules has_schedules ON schedules.id = has_schedules.schedule_id\n		INNER JOIN plugin_ib_educate_bookings bookings ON has_schedules.booking_id = bookings.booking_id\n		INNER JOIN plugin_contacts3_contacts students ON bookings.contact_id = students.id\n		LEFT JOIN plugin_contacts3_family families ON students.family_id = families.family_id\n		LEFT JOIN plugin_contacts3_contacts pcontact ON families.primary_contact_id = pcontact.id\n		LEFT JOIN plugin_contacts3_contact_has_notifications student_mobiles ON students.notifications_group_id = student_mobiles.group_id AND student_mobiles.notification_id = 2\n		LEFT JOIN plugin_contacts3_contact_has_notifications pcontact_notifications ON pcontact.notifications_group_id = pcontact_notifications.group_id AND pcontact_notifications.notification_id = 2\n	WHERE\n		bookings.`delete` = 0 AND bookings.booking_status IN (2, 4) AND\n		has_schedules.deleted = 0 AND has_schedules.booking_status IN (2, 4) AND\n		students.id NOT IN (SELECT\n				students.id\n			FROM plugin_courses_locations rooms\n				INNER JOIN plugin_courses_locations locations ON rooms.parent_id = locations.id\n				INNER JOIN plugin_courses_schedules schedules ON schedules.location_id = rooms.id\n				INNER JOIN plugin_courses_courses courses ON schedules.course_id = courses.id\n				INNER JOIN plugin_courses_categories categories ON courses.category_id = categories.id\n				INNER JOIN plugin_ib_educate_booking_has_schedules has_schedules ON schedules.id = has_schedules.schedule_id\n				INNER JOIN plugin_ib_educate_bookings bookings ON has_schedules.booking_id = bookings.booking_id\n				INNER JOIN plugin_contacts3_contacts students ON bookings.contact_id = students.id\n				LEFT JOIN plugin_contacts3_family families ON students.family_id = families.family_id\n				LEFT JOIN plugin_contacts3_contacts pcontact ON families.primary_contact_id = pcontact.id\n				LEFT JOIN plugin_contacts3_contact_has_notifications student_mobiles ON students.notifications_group_id = student_mobiles.group_id AND student_mobiles.notification_id = 2\n				LEFT JOIN plugin_contacts3_contact_has_notifications pcontact_notifications ON pcontact.notifications_group_id = pcontact_notifications.group_id AND pcontact_notifications.notification_id = 2\n			WHERE\n				bookings.`delete` = 0 AND bookings.booking_status IN (2, 4) AND\n				has_schedules.deleted = 0 AND has_schedules.booking_status IN (2, 4) AND\n				courses.id IN ({!Course Not Booked!})\n			GROUP BY students.id\n		)\n	GROUP BY students.id\n	ORDER BY `Student`',
		`widget_sql` = '',
		`category` = '0',
		`sub_category` = '0',
		`dashboard` = '0',
		`created_by` = null,
		`modified_by` = null,
		`date_created` = NOW(),
		`date_modified` = NOW(),
		`publish` = '1',
		`delete` = '0',
		`widget_id` = NULL,
		`chart_id` = NULL,
		`link_url` = '',
		`link_column` = '',
		`report_type` = 'sql',
		`autoload` = '0',
		`checkbox_column` = '0',
		`action_button_label` = '',
		`action_button` = '0',
		`action_event` = '',
		`checkbox_column_label` = '',
		`autosum` = '0',
		`column_value` = '',
		`autocheck` = '0',
		`custom_report_rules` = '',
		`bulk_message_sms_number_column` = 'Mobile',
		`bulk_message_email_column` = '',
		`bulk_message_subject_column` = '',
		`bulk_message_subject` = '',
		`bulk_message_body_column` = '',
		`bulk_message_body` = 'Our current special offers on supervised study are soon due to expire. Call us on 061-444989 for more information and bookings. Kilmartin Educational Services',
		`bulk_message_interval` = '',
		`rolledback_to_version` = null,
		`php_modifier` = '',
		`generate_documents` = '0',
		`generate_documents_template_file_id` = '0',
		`generate_documents_pdf` = '0',
		`generate_documents_office_print` = '0',
		`generate_documents_office_print_bulk` = '0',
		`generate_documents_tray` = null,
		`generate_documents_helper_method` = '',
		`generate_documents_link_to_contact` = '';

select last_insert_id() into @refid_plugin_reports_reports_20161120231038_001;

insert into `plugin_reports_parameters` set `report_id` = @refid_plugin_reports_reports_20161120231038_001,
		`type` = 'custom',
		`name` = 'Course Not Booked',
		`value` = 'SELECT\n		DISTINCT\n		c.id AS `Course Id`,\n		c.title AS `Course` \n		\n	FROM plugin_courses_schedules s\n		INNER JOIN plugin_courses_courses c ON s.course_id = c.id\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id\n	WHERE \n		s.`delete` = 0 AND c.deleted = 0 AND e.`delete` = 0 AND \n		e.datetime_start >= NOW()\n	ORDER BY c.title',
		`delete` = '0',
		`is_multiselect` = '0';

insert into `plugin_reports_reports`
	set
		`name` = 'Accounts PAYG Reminder',
		`summary` = '',
		`sql` = 'SELECT\n	t.id AS `Transaction Id`,\n	t4.type AS `Transaction Type`,\n	b.booking_id AS `Booking Id`,\n	CONCAT(c3.first_name, \' \', c3.last_name) AS `Booking Name`,\n	emails.`value` AS `Email`,\n	mobiles.`value` AS `Mobile`,\n	CONCAT(c.title,\' \',c.first_name,\' \',c.last_name) AS `Payee`,\n	s.`name` AS `Schedule`,\n        CONCAT(trainer.title,\' \',trainer.first_name,\' \',trainer.last_name) AS `Trainer`,\n	DATE_FORMAT(t.payment_due_date, \'%d/%m/%Y\') AS `Due Date`,\n	t.amount AS `Amount`,\n	(SELECT\n					IFNULL(SUM(IF(t2.credit, t1.amount, -t1.amount)), 0)\n				FROM\n					plugin_bookings_transactions_payments AS `t1`\n					JOIN plugin_bookings_transactions_payments_statuses AS `t2` ON t1.`status` = t2.id\n				WHERE\n			t1.transaction_id = t.id) AS `Paid`,\n	(t.amount - \n		IFNULL(\n			(SELECT\n					SUM(IF(t2.credit, t1.amount, -t1.amount))\n				FROM\n					plugin_bookings_transactions_payments AS `t1`\n					JOIN plugin_bookings_transactions_payments_statuses AS `t2` ON t1.`status` = t2.id\n				WHERE\n			t1.transaction_id = t.id),\n			0\n		)) AS `Amount Due`\n	\nFROM plugin_bookings_transactions `t`\n	INNER JOIN plugin_bookings_transactions_types `t4` ON t4.id = t.type AND t4.credit = 1\n	INNER JOIN plugin_ib_educate_bookings `b` ON t.booking_id = b.booking_id\n	INNER JOIN plugin_contacts3_contacts `c` ON t.contact_id = c.id\n	INNER JOIN plugin_bookings_transactions_has_schedule ts ON t.id = ts.transaction_id AND ts.deleted = 0\n	INNER JOIN plugin_ib_educate_booking_has_schedules bs ON b.booking_id = bs.booking_id AND bs.schedule_id = ts.schedule_id AND bs.deleted = 0\n	INNER JOIN plugin_courses_schedules s ON bs.schedule_id = s.id AND s.`delete` = 0 AND s.payment_type = 2\n	INNER JOIN plugin_courses_courses `c2` ON s.course_id = c2.id\n	INNER JOIN plugin_contacts3_contacts `c3` ON c3.id = b.contact_id\n        INNER JOIN plugin_contacts3_contacts `trainer` ON trainer.id = s.trainer_id\n	LEFT JOIN plugin_contacts3_contact_has_notifications emails ON c3.notifications_group_id = emails.group_id AND emails.notification_id = 1\n	LEFT JOIN plugin_contacts3_contact_has_notifications mobiles ON c3.notifications_group_id = mobiles.group_id AND mobiles.notification_id = 2\n\nWHERE\nt.payment_due_date <= NOW() AND\n(t.payment_due_date >= DATE_SUB(NOW(), INTERVAL 1 DAY) OR DATE_FORMAT(t.payment_due_date, \'%W\') = DATE_FORMAT(NOW(), \'%W\'))\nGROUP BY t.id\nHAVING `Amount Due` > 0',
		`widget_sql` = '',
		`category` = '0',
		`sub_category` = '0',
		`dashboard` = '0',
		`created_by` = null,
		`modified_by` = null,
		`date_created` = now(),
		`date_modified` = now(),
		`publish` = '1',
		`delete` = '0',
		`widget_id` = null,
		`chart_id` = null,
		`link_url` = '',
		`link_column` = '',
		`report_type` = 'sql',
		`autoload` = '0',
		`checkbox_column` = '0',
		`action_button_label` = '',
		`action_button` = '0',
		`action_event` = '',
		`checkbox_column_label` = '',
		`autosum` = '0',
		`column_value` = '',
		`autocheck` = '0',
		`custom_report_rules` = '',
		`bulk_message_sms_number_column` = 'Mobile',
		`bulk_message_email_column` = '',
		`bulk_message_subject_column` = '',
		`bulk_message_subject` = '',
		`bulk_message_body_column` = '',
		`bulk_message_body` = 'Just a reminder that {Booking Name} has an outstanding balance owed to {Trainer} from {Schedule} on {Due Date}. Thank you. Kilmartin Educational Services 061-444989',
		`bulk_message_interval` = '0 0 * * *',
		`rolledback_to_version` = null,
		`php_modifier` = '',
		`generate_documents` = '0',
		`generate_documents_template_file_id` = '0',
		`generate_documents_pdf` = '0',
		`generate_documents_office_print` = '0',
		`generate_documents_office_print_bulk` = '0',
		`generate_documents_tray` = null,
		`generate_documents_helper_method` = '',
		`generate_documents_link_to_contact` = '';

insert into `plugin_reports_reports`
	set
		`name` = 'Accounts PrePay Reminder',
		`summary` = '',
		`sql` = 'SELECT\n	t.id AS `Transaction Id`,\n	t4.type AS `Transaction Type`,\n	b.booking_id AS `Booking Id`,\n	CONCAT(c3.first_name, \' \', c3.last_name) AS `Booking Name`,\n	emails.`value` AS `Email`,\n	mobiles.`value` AS `Mobile`,\n	CONCAT(c.title,\' \',c.first_name,\' \',c.last_name) AS `Payee`,\n	s.`name` AS `Schedule`,\n        CONCAT(trainer.title,\' \',trainer.first_name,\' \',trainer.last_name) AS `Trainer`,\n	DATE_FORMAT(t.payment_due_date, \'%d/%m/%Y\') AS `Due Date`,\n	t.amount AS `Amount`,\n	(SELECT\n					IFNULL(SUM(IF(t2.credit, t1.amount, -t1.amount)), 0)\n				FROM\n					plugin_bookings_transactions_payments AS `t1`\n					JOIN plugin_bookings_transactions_payments_statuses AS `t2` ON t1.`status` = t2.id\n				WHERE\n			t1.transaction_id = t.id) AS `Paid`,\n	(t.amount - \n		IFNULL(\n			(SELECT\n					SUM(IF(t2.credit, t1.amount, -t1.amount))\n				FROM\n					plugin_bookings_transactions_payments AS `t1`\n					JOIN plugin_bookings_transactions_payments_statuses AS `t2` ON t1.`status` = t2.id\n				WHERE\n			t1.transaction_id = t.id),\n			0\n		)) AS `Amount Due`\n	\nFROM plugin_bookings_transactions `t`\n	INNER JOIN plugin_bookings_transactions_types `t4` ON t4.id = t.type AND t4.credit = 1\n	INNER JOIN plugin_ib_educate_bookings `b` ON t.booking_id = b.booking_id\n	INNER JOIN plugin_contacts3_contacts `c` ON t.contact_id = c.id\n	INNER JOIN plugin_bookings_transactions_has_schedule ts ON t.id = ts.transaction_id AND ts.deleted = 0\n	INNER JOIN plugin_ib_educate_booking_has_schedules bs ON b.booking_id = bs.booking_id AND bs.schedule_id = ts.schedule_id AND bs.deleted = 0\n	INNER JOIN plugin_courses_schedules s ON bs.schedule_id = s.id AND s.`delete` = 0 AND s.payment_type = 1\n	INNER JOIN plugin_courses_courses `c2` ON s.course_id = c2.id\n	INNER JOIN plugin_contacts3_contacts `c3` ON c3.id = b.contact_id\n        INNER JOIN plugin_contacts3_contacts `trainer` ON trainer.id = s.trainer_id\n	LEFT JOIN plugin_contacts3_contact_has_notifications emails ON c3.notifications_group_id = emails.group_id AND emails.notification_id = 1\n	LEFT JOIN plugin_contacts3_contact_has_notifications mobiles ON c3.notifications_group_id = mobiles.group_id AND mobiles.notification_id = 2\n\nWHERE\nt.payment_due_date <= NOW()\nGROUP BY t.id\nHAVING `Amount Due` > 0',
		`widget_sql` = '',
		`category` = '0',
		`sub_category` = '0',
		`dashboard` = '0',
		`created_by` = null,
		`modified_by` = null,
		`date_created` = now(),
		`date_modified` = now(),
		`publish` = '1',
		`delete` = '0',
		`widget_id` = null,
		`chart_id` = null,
		`link_url` = '',
		`link_column` = '',
		`report_type` = 'sql',
		`autoload` = '0',
		`checkbox_column` = '0',
		`action_button_label` = '',
		`action_button` = '0',
		`action_event` = '',
		`checkbox_column_label` = '',
		`autosum` = '0',
		`column_value` = '',
		`autocheck` = '0',
		`custom_report_rules` = '',
		`bulk_message_sms_number_column` = 'Mobile',
		`bulk_message_email_column` = '',
		`bulk_message_subject_column` = '',
		`bulk_message_subject` = '',
		`bulk_message_body_column` = '',
		`bulk_message_body` = 'Please note there is an outstanding balance of {Amount Due} on {Booking Name} account for {Schedule}. Payment on this balance is now due. Thank you. Kilmartin Educational Services 061-444989',
		`bulk_message_interval` = '0 0 * * *',
		`rolledback_to_version` = null,
		`php_modifier` = '',
		`generate_documents` = '0',
		`generate_documents_template_file_id` = '0',
		`generate_documents_pdf` = '0',
		`generate_documents_office_print` = '0',
		`generate_documents_office_print_bulk` = '0',
		`generate_documents_tray` = null,
		`generate_documents_helper_method` = '',
		`generate_documents_link_to_contact` = '';

insert into `plugin_reports_reports`
	set
		`name` = 'Accounts PrePay Provisional Booking Reminder',
		`summary` = '',
		`sql` = 'SELECT\n	t.id AS `Transaction Id`,\n	t4.type AS `Transaction Type`,\n	b.booking_id AS `Booking Id`,\n	CONCAT(c3.first_name, \' \', c3.last_name) AS `Booking Name`,\n	emails.`value` AS `Email`,\n	mobiles.`value` AS `Mobile`,\n	CONCAT(c.title,\' \',c.first_name,\' \',c.last_name) AS `Payee`,\n	s.`name` AS `Schedule`,\n        CONCAT(trainer.title,\' \',trainer.first_name,\' \',trainer.last_name) AS `Trainer`,\n	DATE_FORMAT(t.payment_due_date, \'%d/%m/%Y\') AS `Due Date`,\n	t.amount AS `Amount`,\n	(SELECT\n					IFNULL(SUM(IF(t2.credit, t1.amount, -t1.amount)), 0)\n				FROM\n					plugin_bookings_transactions_payments AS `t1`\n					JOIN plugin_bookings_transactions_payments_statuses AS `t2` ON t1.`status` = t2.id\n				WHERE\n			t1.transaction_id = t.id) AS `Paid`,\n	(t.amount - \n		IFNULL(\n			(SELECT\n					SUM(IF(t2.credit, t1.amount, -t1.amount))\n				FROM\n					plugin_bookings_transactions_payments AS `t1`\n					JOIN plugin_bookings_transactions_payments_statuses AS `t2` ON t1.`status` = t2.id\n				WHERE\n			t1.transaction_id = t.id),\n			0\n		)) AS `Amount Due`\n	\nFROM plugin_bookings_transactions `t`\n	INNER JOIN plugin_bookings_transactions_types `t4` ON t4.id = t.type AND t4.credit = 1\n	INNER JOIN plugin_ib_educate_bookings `b` ON t.booking_id = b.booking_id\n	INNER JOIN plugin_contacts3_contacts `c` ON t.contact_id = c.id\n	INNER JOIN plugin_bookings_transactions_has_schedule ts ON t.id = ts.transaction_id AND ts.deleted = 0\n	INNER JOIN plugin_ib_educate_booking_has_schedules bs ON b.booking_id = bs.booking_id AND bs.schedule_id = ts.schedule_id AND bs.deleted = 0\n	INNER JOIN plugin_courses_schedules s ON bs.schedule_id = s.id AND s.`delete` = 0 AND s.payment_type = 1\n	INNER JOIN plugin_courses_courses `c2` ON s.course_id = c2.id\n	INNER JOIN plugin_contacts3_contacts `c3` ON c3.id = b.contact_id\n        INNER JOIN plugin_contacts3_contacts `trainer` ON trainer.id = s.trainer_id\n	LEFT JOIN plugin_contacts3_contact_has_notifications emails ON c3.notifications_group_id = emails.group_id AND emails.notification_id = 1\n	LEFT JOIN plugin_contacts3_contact_has_notifications mobiles ON c3.notifications_group_id = mobiles.group_id AND mobiles.notification_id = 2\n\nWHERE\nt.payment_due_date <= NOW() AND b.created_date >= DATE_SUB(NOW(),INTERVAL 11 MINUTE) AND b.created_date <= DATE_SUB(NOW(),INTERVAL 10 MINUTE)\nGROUP BY t.id\nHAVING `Amount Due` > 0 AND `Paid` = 0',
		`widget_sql` = '',
		`category` = '0',
		`sub_category` = '0',
		`dashboard` = '0',
		`created_by` = null,
		`modified_by` = null,
		`date_created` = now(),
		`date_modified` = now(),
		`publish` = '1',
		`delete` = '0',
		`widget_id` = null,
		`chart_id` = null,
		`link_url` = '',
		`link_column` = '',
		`report_type` = 'sql',
		`autoload` = '0',
		`checkbox_column` = '0',
		`action_button_label` = '',
		`action_button` = '0',
		`action_event` = '',
		`checkbox_column_label` = '',
		`autosum` = '0',
		`column_value` = '',
		`autocheck` = '0',
		`custom_report_rules` = '',
		`bulk_message_sms_number_column` = 'Mobile',
		`bulk_message_email_column` = '',
		`bulk_message_subject_column` = '',
		`bulk_message_subject` = '',
		`bulk_message_body_column` = '',
		`bulk_message_body` = 'Thank you for making a provisional booking for {Schedule}. To secure this booking, payment will be required within twelve hours from now. Thank you. Kilmartin Educational Services 061-444989\n',
		`bulk_message_interval` = '* * * * *',
		`rolledback_to_version` = null,
		`php_modifier` = '',
		`generate_documents` = '0',
		`generate_documents_template_file_id` = '0',
		`generate_documents_pdf` = '0',
		`generate_documents_office_print` = '0',
		`generate_documents_office_print_bulk` = '0',
		`generate_documents_tray` = null,
		`generate_documents_helper_method` = '',
		`generate_documents_link_to_contact` = '';
