/*
ts:2016-11-11 00:09:00
*/

insert into `plugin_reports_reports` set `name` = 'Teacher Daily Class Reminder Automatic',
`summary` = '',
`sql` = 'SELECT\n		e.id AS `Id`,\n		c.title AS `Course`, \n		s.`name` AS `Schedule`, \n		e.datetime_start AS `Date`, \n		CONCAT_WS(\' \', pl.`name`, l.name) AS `Location`,\n		CONCAT_WS(\' \', t.title, t.first_name, t.last_name) AS `Teacher`,\n		n.`value` AS `Mobile`\n	FROM plugin_courses_schedules s\n		INNER JOIN plugin_courses_courses c ON s.course_id = c.id\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id\n		INNER JOIN plugin_contacts3_contacts t ON e.trainer_id = t.id\n		INNER JOIN plugin_contacts3_contact_has_notifications n ON t.notifications_group_id = n.group_id AND n.notification_id = 2\n		LEFT JOIN plugin_courses_locations l ON s.location_id = l.id\n		LEFT JOIN plugin_courses_locations pl ON l.parent_id = pl.id\n	WHERE \n		s.`delete` = 0 AND c.deleted = 0 AND e.`delete` = 0 AND \n		e.datetime_start >= NOW() AND e.datetime_start <= DATE_ADD(NOW(),INTERVAL 1 DAY)',
`widget_sql` = '',
`category` = '0',
`sub_category` = '0',
`dashboard` = '0',
`created_by` = null,
`modified_by` = null,
`date_created` = NOW(),
`date_modified` = NOW(),
`publish` = '1',
`delete` = '0',
`widget_id` = null,
`chart_id` = null,
`link_url` = '',
`link_column` = '',
`report_type` = 'sql',
`autoload` = '0',
`checkbox_column` = '0',
`action_button_label` = '',
`action_button` = '0',
`action_event` = '',
`checkbox_column_label` = '',
`autosum` = '0',
`column_value` = '',
`autocheck` = '0',
`custom_report_rules` = '',
`bulk_message_sms_number_column` = 'Mobile',
`bulk_message_email_column` = '',
`bulk_message_subject_column` = '',
`bulk_message_subject` = '',
`bulk_message_body_column` = '',
`bulk_message_body` = '{Teacher} has a class {Course} / {Schedule} at {Location} on {Date}',
`bulk_message_interval` = '0 0 * * *',
`rolledback_to_version` = null, `php_modifier` = '',
`generate_documents` = '0',
`generate_documents_template_file_id` = '0',
`generate_documents_pdf` = '0',
`generate_documents_office_print` = '0',
`generate_documents_office_print_bulk` = '0',
`generate_documents_tray` = null, `generate_documents_helper_method` = '',
`generate_documents_link_to_contact` = '';

insert into `plugin_reports_reports` set `name` = 'Teacher Class Reminder',
`summary` = '',
`sql` = 'SELECT\n		e.id AS `Id`,\n		c.title AS `Course`, \n		s.`name` AS `Schedule`, \n		e.datetime_start AS `Date`, \n		CONCAT_WS(\' \', pl.`name`, l.name) AS `Location`,\n		CONCAT_WS(\' \', t.title, t.first_name, t.last_name) AS `Teacher`,\n		n.`value` AS `Mobile`\n	FROM plugin_courses_schedules s\n		INNER JOIN plugin_courses_courses c ON s.course_id = c.id\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id\n		INNER JOIN plugin_contacts3_contacts t ON e.trainer_id = t.id\n		INNER JOIN plugin_contacts3_contact_has_notifications n ON t.notifications_group_id = n.group_id AND n.notification_id = 2\n		LEFT JOIN plugin_courses_locations l ON s.location_id = l.id\n		LEFT JOIN plugin_courses_locations pl ON l.parent_id = pl.id\n	WHERE \n		s.`delete` = 0 AND c.deleted = 0 AND e.`delete` = 0 AND \n		e.datetime_start >= NOW() AND e.datetime_start <= DATE_ADD(NOW(),INTERVAL {!Period Before!} {!Period Type!}) AND\n		c.id IN ({!Course!}) AND s.id IN ({!Schedule!}) AND t.id IN ({!Teacher!})',
`widget_sql` = '',
`category` = '0',
`sub_category` = '0',
`dashboard` = '0',
`created_by` = null,
`modified_by` = null,
`date_created` = NOW(),
`date_modified` = NOW(),
`publish` = '1',
`delete` = '0',
`widget_id` = null,
`chart_id` = null,
`link_url` = '',
`link_column` = '',
`report_type` = 'sql',
`autoload` = '0',
`checkbox_column` = '0',
`action_button_label` = '',
`action_button` = '0',
`action_event` = '',
`checkbox_column_label` = '',
`autosum` = '0',
`column_value` = '',
`autocheck` = '0',
`custom_report_rules` = '',
`bulk_message_sms_number_column` = 'Mobile',
`bulk_message_email_column` = '',
`bulk_message_subject_column` = '',
`bulk_message_subject` = '',
`bulk_message_body_column` = '',
`bulk_message_body` = '{Teacher} has a class {Course} / {Schedule} at {Location} on {Date}',
`bulk_message_interval` = '',
`rolledback_to_version` = null,
`php_modifier` = '',
`generate_documents` = '0',
`generate_documents_template_file_id` = '0',
`generate_documents_pdf` = '0',
`generate_documents_office_print` = '0',
`generate_documents_office_print_bulk` = '0',
`generate_documents_tray` = null,
`generate_documents_helper_method` = '',
`generate_documents_link_to_contact` = '';

select last_insert_id() into @refid_plugin_reports_reports_20161111020702_002;
insert into `plugin_reports_parameters` set `report_id` = @refid_plugin_reports_reports_20161111020702_002, `type` = 'dropdown', `name` = 'Period Type', `value` = 'Minute; Hour', `delete` = '0', `is_multiselect` = '0';
	insert into `plugin_reports_parameters` set `report_id` = @refid_plugin_reports_reports_20161111020702_002, `type` = 'text', `name` = 'Period Before', `value` = '10', `delete` = '0', `is_multiselect` = '0';
	insert into `plugin_reports_parameters` set `report_id` = @refid_plugin_reports_reports_20161111020702_002, `type` = 'custom', `name` = 'Course', `value` = '(SELECT\n		DISTINCT\n		c.id AS `Course Id`,\n		c.title AS `Course` \n		\n	FROM plugin_courses_schedules s\n		INNER JOIN plugin_courses_courses c ON s.course_id = c.id\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id\n	WHERE \n		s.`delete` = 0 AND c.deleted = 0 AND e.`delete` = 0 AND \n		e.datetime_start >= NOW()\n	ORDER BY c.title)', `delete` = '0', `is_multiselect` = '1';
	insert into `plugin_reports_parameters` set `report_id` = @refid_plugin_reports_reports_20161111020702_002, `type` = 'custom', `name` = 'Schedule', `value` = '(SELECT\n		DISTINCT\n		s.id AS `Schedule Id`,\n		CONCAT_WS(\' \', s.`name`, \' \', pl.`name`, l.name) AS `Schedule`\n	FROM plugin_courses_schedules s\n		INNER JOIN plugin_courses_courses c ON s.course_id = c.id\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id\n		LEFT JOIN plugin_courses_locations l ON s.location_id = l.id\n		LEFT JOIN plugin_courses_locations pl ON l.parent_id = pl.id\n	WHERE \n		s.`delete` = 0 AND c.deleted = 0 AND e.`delete` = 0 AND \n		e.datetime_start >= NOW() \n	ORDER BY s.`name`)', `delete` = '0', `is_multiselect` = '1';
	insert into `plugin_reports_parameters` set `report_id` = @refid_plugin_reports_reports_20161111020702_002, `type` = 'custom', `name` = 'Teacher', `value` = '(SELECT\n		DISTINCT t.id AS `Id`,\n		CONCAT_WS(\' \', t.title, t.first_name, t.last_name) AS `Teacher`\n	FROM plugin_courses_schedules s\n		INNER JOIN plugin_courses_courses c ON s.course_id = c.id\n		INNER JOIN plugin_courses_schedules_events e ON s.id = e.schedule_id\n		INNER JOIN plugin_contacts3_contacts t ON e.trainer_id = t.id\n	WHERE \n		s.`delete` = 0 AND c.deleted = 0 AND e.`delete` = 0 AND \n		e.datetime_start >= NOW()\nORDER BY `Teacher`)', `delete` = '0', `is_multiselect` = '1';
