/*
ts:2019-01-29 00:00:01
*/

UPDATE `plugin_reports_reports` SET `sql`='SELECT\r\n		tx.`Schedule`,\r\n		tx.category AS `Category`,\r\n		SUM(tx.Total) AS `Total`,\r\n		SUM(tx.Paid) AS `Paid`,\r\n		SUM(tx.Outstanding) AS `Outstanding`\r\n	FROM (SELECT\r\n	t.id as `Transaction ID`,\r\n	tt.type as `Transaction Type`,\r\n	b.booking_id as `Booking ID`,\r\n	CONCAT_WS(\' \', c.first_name, c.last_name) as Student,\r\n	CONCAT_WS(\' \', cp.first_name, cp.last_name) as Payee,\r\n	emailss.`value` as `Email`,\r\n	mobiless.`value` as `Mobile`,\r\n	s.`name` as `Schedule`,\r\n	o.title as `Course`,\r\n	a.category as `Category`,\r\n	t.total as `Total`,\r\n	IFNULL(IF(ps.credit = 1, 1, -1) * p.amount, 0) as `Paid`,\r\n	t.total - IFNULL(SUM(IF(ps.credit = 1, 1, -1) * p.amount), 0) as `Outstanding`,\r\n	t.payment_due_date as `Due Date`,\r\n	t.contact_id,\r\n	hs.schedule_id\r\nFROM plugin_bookings_transactions `t`\r\n	LEFT JOIN plugin_bookings_transactions_types `tt` ON tt.id = t.type\r\n	INNER JOIN plugin_ib_educate_bookings `b` ON t.booking_id = b.booking_id AND b.`delete` = 0\r\n	LEFT JOIN plugin_bookings_transactions_payments p on t.id = p.transaction_id AND p.deleted = 0\r\n	LEFT JOIN plugin_bookings_transactions_payments_statuses ps on p.`status` = ps.id\r\n	LEFT JOIN plugin_contacts3_contacts c on b.contact_id = c.id\r\n	LEFT JOIN plugin_contacts3_contacts cp on t.contact_id = cp.id\r\n	LEFT JOIN plugin_bookings_transactions_has_schedule hs on t.id = hs.transaction_id AND hs.deleted = 0\r\n	LEFT JOIN plugin_ib_educate_booking_has_schedules bs on b.booking_id = bs.booking_id AND hs.schedule_id = bs.schedule_id AND bs.deleted = 0\r\n	INNER JOIN plugin_courses_schedules s on bs.schedule_id = s.id\r\n	LEFT JOIN plugin_courses_courses o on s.course_id = o.id\r\n	LEFT JOIN plugin_courses_categories a ON o.category_id = a.id\r\n	LEFT JOIN (select ce.id, emails.`value` from plugin_contacts3_contacts ce inner join plugin_contacts3_contact_has_notifications emails ON ce.notifications_group_id = emails.group_id AND emails.notification_id = 1 AND emails.deleted = 0 group by ce.id) emailss on cp.id = emailss.id\r\n	LEFT JOIN (select cm.id, mobiles.`value` from plugin_contacts3_contacts cm inner join plugin_contacts3_contact_has_notifications mobiles ON cm.notifications_group_id = mobiles.group_id AND mobiles.notification_id = 2 AND mobiles.deleted = 0 group by cm.id) mobiless on cp.id = mobiless.id\r\nWHERE t.deleted = 0 AND t.type IN (1,2) AND (o.category_id = \'{!Category!}\' or \'\' = \'{!Category!}\')\r\nGROUP BY t.id\r\n) tx\r\nGROUP BY tx.`Schedule`' WHERE (`name`='Outstanding By Schedule');
INSERT INTO `plugin_reports_parameters` (`report_id`, `type`, `name`, `value`) VALUES ((select id from plugin_reports_reports where name='Outstanding By Schedule'), 'custom', 'Category', 'select id, category from plugin_courses_categories c order by c.category');

UPDATE `plugin_reports_parameters` SET `value`='(select 0 as id, \'All\' as Schedule)\r\nUNION ALL\r\n(select distinct s.id, s.name as Schedule from plugin_courses_schedules s inner join plugin_courses_schedules_events t on t.schedule_id = s.id inner join plugin_ib_educate_booking_items i on  t.id = i.period_id where s.`delete` = 0 and i.`delete` = 0 order by s.name)' WHERE (`name`='schedule_id' and report_id in (select id from plugin_reports_reports where name='Outstanding Transactions' and `delete`=0));

