/*
ts:2016-02-10 22:27:00
*/

-- KES-1344
INSERT INTO `plugin_reports_reports` SET `name` = 'Blackout Timeslot Clear', `summary` = '', `sql` = 'SELECT sch.name AS `schedule`, sev.* \n	FROM plugin_courses_schedules_events sev\n		INNER JOIN engine_calendar_events cev \n			ON CAST(sev.datetime_start AS DATE) >= CAST(cev.start_date AS DATE) AND CAST(sev.datetime_start AS DATE) <= CAST(cev.end_date AS DATE)\n		INNER JOIN engine_calendar_rules cru ON cev.rule_id = cru.id AND cru.plugin_name = \'courses\' AND cru.publish = 1 AND cru.deleted = 0\n		INNER JOIN engine_calendar_types ct ON cev.type_id = ct.id\n                INNER JOIN plugin_courses_schedules sch ON sev.schedule_id = sch.id\n	WHERE sev.`delete` = 0 AND cev.id in ({!event_id!})', `widget_sql` = '', `category` = '0', `sub_category` = '0', `dashboard` = '0', `created_by` = null, `modified_by` = null, `date_created` = NOW(), `date_modified` = NOW(), `publish` = '1', `delete` = '0', `widget_id` = '28', `chart_id` = '23', `link_url` = '', `link_column` = '', `report_type` = 'sql', `autoload` = '0', `checkbox_column` = '1', `action_button_label` = 'clear time slots', `action_button` = '1', `action_event` = 'if (confirm(\'Are you sure you want to delete?\')){\nvar $reportRows = $(\"#report_table tbody > tr\");\nvar deleteEventIds = [];\nfor (var i = 0 ; i < $reportRows.length ; ++i) {\n	var $td = $($reportRows[i]).find(\"td\");\n    if ($($reportRows[i]).find(\".row_check\")[0].checked){\n		deleteEventIds.push($td[1].innerHTML);\n	 }\n}\n\nvar data = {events: JSON.stringify(deleteEventIds)};\n$.post(\'/admin/courses/bulk_delete_schedule_events\', data, function(response){\n    //alert(response.message);\n$(\"#generate_report\").click();\n});\n}', `checkbox_column_label` = 'clear', `autosum` = '0', `column_value` = '', `autocheck` = '1', `custom_report_rules` = '', `bulk_message_sms_number_column` = '', `bulk_message_email_column` = '', `bulk_message_subject_column` = '', `bulk_message_subject` = '', `bulk_message_body_column` = '', `bulk_message_body` = '', `bulk_message_interval` = '', `rolledback_to_version` = null, `php_modifier` = '';
	SELECT last_insert_id() INTO @refid_plugin_reports_reports_20160211002432_001;
	INSERT INTO `plugin_reports_parameters` SET `report_id` = @refid_plugin_reports_reports_20160211002432_001, `type` = 'custom', `name` = 'event_id', `value` = 'SELECT ce.id, CONCAT_WS(\' \',ce.title,cr.plugin_name,cr.title,ct.title,CAST(ce.start_date AS DATE)) AS ev\n	FROM engine_calendar_events ce\n		INNER JOIN engine_calendar_rules cr ON ce.rule_id = cr.id\n		INNER JOIN engine_calendar_types ct ON ce.type_id = ct.id\n	WHERE ce.deleted = 0 AND cr.deleted = 0 AND ct.deleted = 0', `delete` = 0, `is_multiselect` = 0;

