/*
ts:2016-04-19 21:04:00
*/

insert into `plugin_reports_reports`
  set
    `name` = 'Products SEO Report',
    `summary` = '',
    `sql` = 'select \n		c.category,\n		p.title,\n		p.url_title,\n		concat(\'/products.html/\',replace(c.category, \' \', \'-\'), \'/\', p.url_title) as `relative_url`,\n		p.brief_description,\n		replace(replace(p.description, \'<\', \'&lt;\'), \'>\', \'&gt;\') as `description`,\n		p.seo_title,\n		p.seo_keywords,\n		p.seo_description,\n		p.seo_footer ,\n		group_concat(concat(\'<a href=\"/shared_media/ambersos/media/photos/products/\', i.file_name, \'\">\', i.file_name,\'</a><br />\'), \"\\n\") as images\n	from plugin_products_product p\n		left join plugin_products_product_categories pc on p.id = pc.product_id\n		left join plugin_products_category c on pc.category_id = c.id\n		left join plugin_products_product_images i on p.id = i.product_id\n	group by p.id\n	order by c.category,p.title',
    `widget_sql` = '',
    `category` = '0',
    `sub_category` = '0',
    `dashboard` = '0',
    `date_created` = NOW(),
    `date_modified` = NOW(),
    `publish` = '1',
    `delete` = '0',
    `widget_id` = null,
    `chart_id` = null,
    `link_url` = '',
    `link_column` = '',
    `report_type` = 'sql',
    `autoload` = '0',
    `checkbox_column` = '0',
    `action_button_label` = '',
    `action_button` = '0',
    `action_event` = '',
    `checkbox_column_label` = '',
    `autosum` = '0',
    `column_value` = '',
    `autocheck` = '0',
    `custom_report_rules` = '',
    `bulk_message_sms_number_column` = '',
    `bulk_message_email_column` = '',
    `bulk_message_subject_column` = '',
    `bulk_message_subject` = '',
    `bulk_message_body_column` = '',
    `bulk_message_body` = '',
    `bulk_message_interval` = '',
    `rolledback_to_version` = null,
    `php_modifier` = '',
    `generate_documents` = '0',
    `generate_documents_template_file_id` = '0',
    `generate_documents_pdf` = '0',
    `generate_documents_office_print` = '0',
    `generate_documents_office_print_bulk` = '0',
    `generate_documents_tray` = null,
    `generate_documents_helper_method` = '',
    `generate_documents_link_to_contact` = '';

