/*
ts:2016-09-06 10:37:00
*/

INSERT INTO `plugin_reports_reports` 
  SET 
    `name` = 'Course Bookings Outstanding',
    `summary` = '',
    `sql` = 'SELECT \n		CONCAT_WS(\' \', students.title, students.first_name, students.last_name) AS `Student Name`, \n		CONCAT_WS(\' \', students.address1, students.address1, students.address1 ) AS `Address`,\n		CONCAT_WS(\' \', parents.title, parents.first_name, parents.last_name) AS `Parent Name`, \n		`courses`.`title` AS `Course`, \n		`schedules`.`name` AS `Schedule`, \n		`tx`.created AS `Date Created`,\n		has_schedules.`status` AS `Booking Status`,\n		IF(bookings.total, bookings.total, has_schedules.total) AS `Total`, \n		`outstanding`.`outstanding` AS `Outstanding Amount`\n	FROM `plugin_courses_bookings` AS `bookings` \n		INNER JOIN `plugin_contacts_contact` AS `students` ON (`bookings`.`student_id` = `students`.`id`) \n		LEFT JOIN `plugin_family_members` AS `fmembers` ON (`students`.id = `fmembers`.`contact_id`)\n		LEFT JOIN `plugin_family_families` AS `families` ON (`fmembers`.`family_id` = `families`.`id`)\n		LEFT JOIN `plugin_contacts_contact` AS `parents` ON (`families`.`primary_contact_id` = `parents`.`id`)\n		INNER JOIN `plugin_courses_bookings_has_schedules` AS `has_schedules` ON (`bookings`.`id` = `has_schedules`.`booking_id`) \n		INNER JOIN `plugin_courses_bookings_has_schedules_has_timeslots` AS `has_timeslots` ON (`has_schedules`.`id` = `has_timeslots`.`booking_has_schedule_id`) \n		INNER JOIN `plugin_courses_schedules` AS `schedules` ON (`has_schedules`.`schedule_id` = `schedules`.`id`) \n		INNER JOIN `plugin_courses_schedules_events` AS `timeslots` ON (`has_timeslots`.`timeslot_id` = `timeslots`.`id`) \n		INNER JOIN `plugin_courses_courses` AS `courses` ON (`schedules`.`course_id` = `courses`.`id`) \n		LEFT JOIN `plugin_courses_categories` AS `ccategories` ON (`courses`.`category_id` = `ccategories`.`id`) \n		LEFT JOIN `plugin_courses_bookings_has_transactions` AS `has_tx` ON (`bookings`.`id` = `has_tx`.`booking_id` AND `has_tx`.`deleted` = 0) \n		INNER JOIN `plugin_transactions_transactions` AS `tx` ON (`has_tx`.`transaction_id` = `tx`.`id` AND `tx`.`deleted` = 0) \n		INNER JOIN `plugin_transactions_transactions_outstanding` AS `outstanding` ON (`tx`.`id` = `outstanding`.`transaction_id`) \n	WHERE `bookings`.`deleted` = 0 AND `has_schedules`.`deleted` = 0 AND `has_timeslots`.`deleted` = 0  AND `outstanding`.`outstanding` > 0 AND bookings.`status` != \'Cancelled\' AND has_schedules.`status` != \'Cancelled\'\n	GROUP BY `bookings`.`id`, `has_schedules`.`id` \n	ORDER BY `bookings`.`updated`',
    `widget_sql` = '',
    `category` = '0',
    `sub_category` = '0',
    `dashboard` = '0',
    `created_by` = null,
    `modified_by` = null,
    `date_created` = NOW(),
    `date_modified` = NOW(),
    `publish` = '1',
    `delete` = '0',
    `widget_id` = null,
    `chart_id` = null,
    `link_url` = '',
    `link_column` = '',
    `report_type` = 'sql',
    `autoload` = '0',
    `checkbox_column` = '0',
    `action_button_label` = '',
    `action_button` = '0',
    `action_event` = '',
    `checkbox_column_label` = 'Total Outstanding',
    `autosum` = '1',
    `column_value` = 'Outstanding Amount',
    `autocheck` = '0',
    `custom_report_rules` = 'var total = 0.0;\n    var $tr = $(\'#report_table tbody tr\');\n	$tr.each(function(){\n		var value = parseFloat($(this).find(\"td:last\").html());\n		total += value;\n	});\n	$(\'input.total_settlement\').val(total.toFixed(2));',
    `bulk_message_sms_number_column` = '',
    `bulk_message_email_column` = '',
    `bulk_message_subject_column` = '',
    `bulk_message_subject` = '',
    `bulk_message_body_column` = '',
    `bulk_message_body` = '',
    `bulk_message_interval` = '',
    `rolledback_to_version` = null,
    `php_modifier` = '',
    `generate_documents` = '0',
    `generate_documents_template_file_id` = '0',
    `generate_documents_pdf` = '0',
    `generate_documents_office_print` = '0',
    `generate_documents_office_print_bulk` = '0',
    `generate_documents_tray` = null,
    `generate_documents_helper_method` = '',
    `generate_documents_link_to_contact` = '';
