/*
ts:2020-10-01 11:30:00
*/

ALTER TABLE `plugin_contacts3_notes`
  ADD COLUMN `gdpr_cleansed_datetime`  datetime NULL AFTER `deleted`,
  ADD COLUMN `gdpr_cleansed_by_report_id`  int NULL AFTER `gdpr_cleansed_datetime`;

UPDATE `plugin_reports_reports` SET `sql`='select \r\n		has_delegates.contact_id as `Contact ID`, students.first_name as `First Name`, students.last_name as `Last Name`, min(timeslots.datetime_end) as first_timeslot_date\r\n	from plugin_ib_educate_bookings bookings\r\n		inner join plugin_ib_educate_bookings_has_delegates has_delegates on bookings.booking_id = has_delegates.booking_id\r\n		inner join plugin_ib_educate_booking_items items on bookings.booking_id = items.booking_id\r\n		inner join plugin_courses_schedules_events timeslots on items.period_id = timeslots.id\r\n		inner join plugin_contacts3_contacts students on has_delegates.contact_id = students.id\r\n		inner join plugin_courses_schedules schedules on timeslots.schedule_id = schedules.id\r\n		inner join plugin_courses_courses courses on schedules.course_id = courses.id\r\n		inner join plugin_courses_types ctypes on courses.type_id = ctypes.id\r\n	where bookings.`delete` = 0 and has_delegates.deleted = 0 and items.`delete` = 0 and timeslots.`delete` = 0 and students.gdpr_cleansed_datetime is null \r\n	group by `Contact ID`\r\n	having first_timeslot_date < date_sub(\'{!date!}\', interval 365 day)\r\n' WHERE (`name`='GDPR cleanse - Application');
UPDATE `plugin_reports_reports` SET `sql`='select \r\n		survey_answers.id as `Survey Result Answer ID`, questions.title as `Question`, survey_answers.textbox_value as `Answer`, FROM_UNIXTIME(survey_results.starttime) `Survey Datetime`\r\n	from plugin_survey_result survey_results\r\n		inner join plugin_survey_answer_result survey_answers on survey_results.id = survey_answers.survey_result_id\r\n		inner join plugin_survey_questions questions on survey_answers.question_id = questions.id\r\n		\r\n	where survey_answers.textbox_value <> \'GDPR\' and questions.title in (\'Firstname\', \'Lastname\', \'Name\', \'Email\', \'Phone\', \'Mobile\') and from_unixtime(survey_results.starttime) < date_sub(\'{!date!}\', interval 12 month);' WHERE (`name`='GDPR cleanse - Survey');
