/*
ts:2018-01-31 20:23:00
*/

UPDATE `plugin_reports_reports`
  SET
    `sql`='select\n	`event`.`name` `Details`,\n	DATE_FORMAT(min(`date`.`starts`), \'%e/%c/%Y\') `Date`,\n	concat(REPLACE(REPLACE(`item`.`currency`, \'EUR\', \'€\'), \'GBP\', \'£\'), format(sum(`item`.`commission` * `item`.`quantity`), 2)) `Amount`,\n        \'23%\' `VAT Rate`,\n	concat(REPLACE(REPLACE(`item`.`currency`, \'EUR\', \'€\'), \'GBP\', \'£\'), format(sum(`item`.`vat` * `item`.`quantity`), 2)) `VAT`,\n	concat(REPLACE(REPLACE(`item`.`currency`, \'EUR\', \'€\'), \'GBP\', \'£\'), format(sum((`item`.`vat` + `item`.`commission`) * `item`.`quantity`), 2)) `Total`\nfrom `plugin_events_orders_items`                 `item`\nleft join `plugin_events_events_has_ticket_types` `ticket_type` on `item`.`ticket_type_id`  = `ticket_type`.`id`\nleft join `plugin_events_events`                  `event`       on `ticket_type`.`event_id` = `event`.`id`\nleft join `plugin_events_events_dates`            `date`        on `date`.`event_id` = `event`.`id`\nleft join `plugin_events_orders`                  `order`       on `item`.`order_id` = `order`.`id` \nwhere `event`.`deleted` = 0  and `order`.status = \'PAID\'\nand `date`.`deleted` = 0 \r\nand `date`.`starts` BETWEEN cast(\'{!month_range_from!}\' as date) AND cast(\'{!month_range_to!}\' as date)\ngroup by `event`.`id`\norder by `event`.`id` desc\r\n'
  WHERE (`name`='VAT Report');

UPDATE `plugin_reports_reports`
  SET `sql`='select\r\n	`events`.`name` `Details`,\r\n	DATE_FORMAT(`items_filtered`.`starts`, \'%e/%c/%Y\') `Date`,\r\n	concat(REPLACE(REPLACE(`items`.`currency`, \'EUR\', \'€\'), \'GBP\', \'£\'), format(sum(`items`.`commission` * `items`.`quantity`), 2)) `Amount`,\r\n        \'23%\' `VAT Rate`,\r\n	concat(REPLACE(REPLACE(`items`.`currency`, \'EUR\', \'€\'), \'GBP\', \'£\'), format(sum(`items`.`vat` * `items`.`quantity`), 2)) `VAT`,\r\n	concat(REPLACE(REPLACE(`items`.`currency`, \'EUR\', \'€\'), \'GBP\', \'£\'), format(sum((`items`.`vat` + `items`.`commission`) * `items`.`quantity`), 2)) `Total`\r\nfrom `plugin_events_orders_items` `items`\r\ninner join `plugin_events_events_has_ticket_types` `ticket_type` on `items`.`ticket_type_id`  = `ticket_type`.`id`\r\ninner join `plugin_events_events` `events`       on `ticket_type`.`event_id` = `events`.`id`\r\ninner join `plugin_events_orders` `orders`       on `items`.`order_id` = `orders`.`id` \r\ninner join (select\r\n	items.id, min(dates.`starts`) as starts\r\nfrom plugin_events_orders_items items\r\ninner join plugin_events_orders_items_has_dates hdates on items.id = hdates.order_item_id\r\ninner join plugin_events_events_dates dates on hdates.date_id = dates.id\r\ninner join plugin_events_orders orders on items.order_id = orders.id\r\nwhere `dates`.`deleted` = 0 and `dates`.`starts` BETWEEN \'{!month_range_from!}\' AND \'{!month_range_to!}\' and orders.`status` = \'PAID\'\r\ngroup by items.id\r\n) items_filtered on items.id = items_filtered.id\r\nwhere `events`.`deleted` = 0  and `orders`.status = \'PAID\'\r\ngroup by `events`.`id`\r\norder by `events`.`id` desc'
  WHERE (`name`='VAT Report');
