/*
ts:2018-01-03 14:40:00
*/

INSERT INTO `plugin_reports_reports` (`name`, `sql`, `publish`, `delete`, `report_type`, `php_post_filter`) VALUES ('VAT Report', 'select `Details`, `Date`, `Amount`, `VAT Rate`, `Total` FROM (\r\n\r\nselect\r\n	`event`.`id`,\r\n	`event`.`name` `Details`,\r\n	\'Date\' `Date`,\r\n	\'Amount\' `Amount`,\r\n	CONCAT(`order`.`vat_rate`, \'%\') `VAT Rate`,\r\n	\'Total\' `Total`\r\nfrom `plugin_events_orders_items`                 `item`\r\nleft join `plugin_events_events_has_ticket_types` `ticket_type` on `item`.`ticket_type_id`  = `ticket_type`.`id`\r\nleft join `plugin_events_events`                  `event`       on `ticket_type`.`event_id` = `event`.`id`\r\nleft join `plugin_events_events_dates`            `date`        on `date`.`event_id` = `event`.`id`\r\nleft join `plugin_events_orders`                  `order`       on `item`.`order_id` = `order`.`id` \r\nwhere `event`.`deleted` = 0\r\nand `date`.`deleted` = 0 \r\ngroup by `event`.`id`\r\nhaving min(`date`.`starts`) BETWEEN cast(\'{!month_range_from!}\' as date) AND cast(\'{!month_range_to!}\' as date)\r\n\r\nunion select\r\n	`event`.`id`,\r\n	\'\' `Details`,\r\n	DATE_FORMAT(min(`date`.`starts`), \'%e/%c/%Y\') `Date`,\r\n	concat(REPLACE(REPLACE(`item`.`currency`, \'EUR\', \'€\'), \'GBP\', \'£\'), format(sum(`item`.`price` * `item`.`quantity` - `item`.`vat` * `item`.`quantity`), 2)) `Amount`,\r\n	concat(REPLACE(REPLACE(`item`.`currency`, \'EUR\', \'€\'), \'GBP\', \'£\'), format(sum(`item`.`vat` * `item`.`quantity`), 2)) `VAT Rate`,\r\n	concat(REPLACE(REPLACE(`item`.`currency`, \'EUR\', \'€\'), \'GBP\', \'£\'), format(sum(`item`.`price` * `item`.`quantity`), 2)) `Total`\r\nfrom `plugin_events_orders_items`                 `item`\r\nleft join `plugin_events_events_has_ticket_types` `ticket_type` on `item`.`ticket_type_id`  = `ticket_type`.`id`\r\nleft join `plugin_events_events`                  `event`       on `ticket_type`.`event_id` = `event`.`id`\r\nleft join `plugin_events_events_dates`            `date`        on `date`.`event_id` = `event`.`id`\r\nleft join `plugin_events_orders`                  `order`       on `item`.`order_id` = `order`.`id` \r\nwhere `event`.`deleted` = 0\r\nand `date`.`deleted` = 0 \r\ngroup by `event`.`id`\r\nhaving min(`date`.`starts`) BETWEEN cast(\'{!month_range_from!}\' as date) AND cast(\'{!month_range_to!}\' as date)\r\n\r\n) `t`\r\norder by `id`, `Details` desc', '1', '0', 'sql', '$t_amount = 0;\r\n$t_vat = 0;\r\n$t_total = 0;\r\nforeach ($data as $i => $row) {\r\n	if ($i % 2 == 1) {\r\n\r\n		$t_amount += (float)str_replace(array(\"€\", \",\"), \"\", $row[\"Amount\"]);\r\n		$t_vat += (float)str_replace(array(\"€\", \",\"), \"\", $row[\"VAT Rate\"]);\r\n		$t_total += (float)str_replace(array(\"€\", \",\"), \"\", $row[\"Total\"]);\r\n\r\n	}\r\n}\r\n\r\n$data[] = array(\r\n	\"TOTAL\",\r\n	\" \",\r\n	\"€\" . number_format($t_amount, 2),\r\n	\"€\" . number_format($t_vat, 2),\r\n	\"€\" . number_format($t_total, 2)\r\n);');
INSERT INTO plugin_reports_parameters
  (report_id, `type`, name, `value`, `delete`, `is_multiselect`)
  (select id, 'month', 'Month', '', 0, 0 from plugin_reports_reports where `name` = 'VAT Report' and `delete` = 0);

UPDATE `plugin_reports_reports`
  SET
    `sql`='select\n	`event`.`name` `Details`,\n	DATE_FORMAT(min(`date`.`starts`), \'%e/%c/%Y\') `Date`,\n	concat(REPLACE(REPLACE(`item`.`currency`, \'EUR\', \'€\'), \'GBP\', \'£\'), format(sum(`item`.`commission` * `item`.`quantity`), 2)) `Amount`,\n        \'23%\' `VAT Rate`,\n	concat(REPLACE(REPLACE(`item`.`currency`, \'EUR\', \'€\'), \'GBP\', \'£\'), format(sum(`item`.`vat` * `item`.`quantity`), 2)) `VAT`,\n	concat(REPLACE(REPLACE(`item`.`currency`, \'EUR\', \'€\'), \'GBP\', \'£\'), format(sum((`item`.`vat` + `item`.`commission`) * `item`.`quantity`), 2)) `Total`\nfrom `plugin_events_orders_items`                 `item`\nleft join `plugin_events_events_has_ticket_types` `ticket_type` on `item`.`ticket_type_id`  = `ticket_type`.`id`\nleft join `plugin_events_events`                  `event`       on `ticket_type`.`event_id` = `event`.`id`\nleft join `plugin_events_events_dates`            `date`        on `date`.`event_id` = `event`.`id`\nleft join `plugin_events_orders`                  `order`       on `item`.`order_id` = `order`.`id` \nwhere `event`.`deleted` = 0\nand `date`.`deleted` = 0 \ngroup by `event`.`id`\nhaving min(`date`.`starts`) BETWEEN cast(\'{!month_range_from!}\' as date) AND cast(\'{!month_range_to!}\' as date)\norder by `event`.`id` desc\r\n',
    `php_post_filter`='$t_amount = 0;\n$t_vat = 0;\n$t_total = 0;\nforeach ($data as $i => $row) {\n		$t_amount += (float)str_replace(array(\"€\", \",\"), \"\", $row[\"Amount\"]);\n		$t_vat += (float)str_replace(array(\"€\", \",\"), \"\", $row[\"VAT\"]);\n		$t_total += (float)str_replace(array(\"€\", \",\"), \"\", $row[\"Total\"]);\n}\n\n$data[] = array(\n	\"TOTAL\",\n	\" \",\n  \"€\" . number_format($t_amount, 2),\n	\"23%\",\n	\"€\" . number_format($t_vat, 2),\n	\"€\" . number_format($t_total, 2)\n);'
    WHERE (`name`='VAT Report');

