/*
ts:2016-10-19 10:43:00
*/

insert into engine_countries (`name`) values ('Albania');
insert into engine_countries (`name`) values ('Algeria');
insert into engine_countries (`name`) values ('Andorra');
insert into engine_countries (`name`) values ('Argentina');
insert into engine_countries (`name`) values ('Aruba');
insert into engine_countries (`name`) values ('Australia');
insert into engine_countries (`name`) values ('Austria');
insert into engine_countries (`name`) values ('Azerbaijan');
insert into engine_countries (`name`) values ('Bahrain');
insert into engine_countries (`name`) values ('Barbados');
insert into engine_countries (`name`) values ('Belarus');
insert into engine_countries (`name`) values ('Belgium');
insert into engine_countries (`name`) values ('Bermuda');
insert into engine_countries (`name`) values ('Bosnia');
insert into engine_countries (`name`) values ('Botswana');
insert into engine_countries (`name`) values ('Brazil');
insert into engine_countries (`name`) values ('Brazil - Bonaire');
insert into engine_countries (`name`) values ('Brunei');
insert into engine_countries (`name`) values ('Bulgaria');
insert into engine_countries (`name`) values ('Canada');
insert into engine_countries (`name`) values ('Cayman Islands');
insert into engine_countries (`name`) values ('Chile');
insert into engine_countries (`name`) values ('China');
insert into engine_countries (`name`) values ('Colombia');
insert into engine_countries (`name`) values ('Costa Rica');
insert into engine_countries (`name`) values ('Croatia');
insert into engine_countries (`name`) values ('Cuba');
insert into engine_countries (`name`) values ('Cyprus');
insert into engine_countries (`name`) values ('Czech Republic');
insert into engine_countries (`name`) values ('Denmark');
insert into engine_countries (`name`) values ('Dominican Rep.');
insert into engine_countries (`name`) values ('Ecuador');
insert into engine_countries (`name`) values ('Egypt');
insert into engine_countries (`name`) values ('Estonia');
insert into engine_countries (`name`) values ('Faroe Islands');
insert into engine_countries (`name`) values ('Finland');
insert into engine_countries (`name`) values ('French Polynesia');
insert into engine_countries (`name`) values ('Georgia');
insert into engine_countries (`name`) values ('Germany');
insert into engine_countries (`name`) values ('Ghana');
insert into engine_countries (`name`) values ('Gibraltar');
insert into engine_countries (`name`) values ('Greece');
insert into engine_countries (`name`) values ('Guadeloupe');
insert into engine_countries (`name`) values ('Guam');
insert into engine_countries (`name`) values ('Guernsey');
insert into engine_countries (`name`) values ('Hong Kong');
insert into engine_countries (`name`) values ('Hungary');
insert into engine_countries (`name`) values ('Iceland');
insert into engine_countries (`name`) values ('India');
insert into engine_countries (`name`) values ('Indonesia');
insert into engine_countries (`name`) values ('Ireland - (Republic Of)');
insert into engine_countries (`name`) values ('Isle Of Man');
insert into engine_countries (`name`) values ('Israel');
insert into engine_countries (`name`) values ('Italy');
insert into engine_countries (`name`) values ('Jamaica');
insert into engine_countries (`name`) values ('Japan');
insert into engine_countries (`name`) values ('Jersey');
insert into engine_countries (`name`) values ('Jordan');
insert into engine_countries (`name`) values ('Kazakhstan');
insert into engine_countries (`name`) values ('Kenya');
insert into engine_countries (`name`) values ('Korea (SOUTH)');
insert into engine_countries (`name`) values ('Kuwait');
insert into engine_countries (`name`) values ('Latvia');
insert into engine_countries (`name`) values ('Lebanon');
insert into engine_countries (`name`) values ('Liechtenstein');
insert into engine_countries (`name`) values ('Lithuania');
insert into engine_countries (`name`) values ('Luxembourg');
insert into engine_countries (`name`) values ('Macedonia');
insert into engine_countries (`name`) values ('Malaysia');
insert into engine_countries (`name`) values ('Maldives');
insert into engine_countries (`name`) values ('Malta');
insert into engine_countries (`name`) values ('Mauritius');
insert into engine_countries (`name`) values ('Mexico');
insert into engine_countries (`name`) values ('Moldova, Republic Of');
insert into engine_countries (`name`) values ('Monaco');
insert into engine_countries (`name`) values ('Montenegro');
insert into engine_countries (`name`) values ('Morocco');
insert into engine_countries (`name`) values ('Mozambique');
insert into engine_countries (`name`) values ('Nepal');
insert into engine_countries (`name`) values ('Netherlands');
insert into engine_countries (`name`) values ('New Zealand');
insert into engine_countries (`name`) values ('Nigeria');
insert into engine_countries (`name`) values ('Norway');
insert into engine_countries (`name`) values ('Oman');
insert into engine_countries (`name`) values ('Pakistan');
insert into engine_countries (`name`) values ('Papua New Guinea');
insert into engine_countries (`name`) values ('Paraguay');
insert into engine_countries (`name`) values ('Peru');
insert into engine_countries (`name`) values ('Philippines');
insert into engine_countries (`name`) values ('Poland');
insert into engine_countries (`name`) values ('Portugal');
insert into engine_countries (`name`) values ('Puerto Rico');
insert into engine_countries (`name`) values ('Qatar');
insert into engine_countries (`name`) values ('Reunion');
insert into engine_countries (`name`) values ('Romania');
insert into engine_countries (`name`) values ('Russia');
insert into engine_countries (`name`) values ('Saint Lucia');
insert into engine_countries (`name`) values ('Saint Vincent');
insert into engine_countries (`name`) values ('Saudi Arabia');
insert into engine_countries (`name`) values ('Serbia');
insert into engine_countries (`name`) values ('Singapore');
insert into engine_countries (`name`) values ('Slovakia');
insert into engine_countries (`name`) values ('Slovenia');
insert into engine_countries (`name`) values ('South Africa');
insert into engine_countries (`name`) values ('Sri Lanka');
insert into engine_countries (`name`) values ('St Kitts & Nevis');
insert into engine_countries (`name`) values ('Sweden');
insert into engine_countries (`name`) values ('Switzerland');
insert into engine_countries (`name`) values ('Taiwan');
insert into engine_countries (`name`) values ('Tanzania');
insert into engine_countries (`name`) values ('Thailand');
insert into engine_countries (`name`) values ('Tunisia');
insert into engine_countries (`name`) values ('Turkey');
insert into engine_countries (`name`) values ('United Arab Emrates');
insert into engine_countries (`name`) values ('Uganda');
insert into engine_countries (`name`) values ('Ukraine');
insert into engine_countries (`name`) values ('United States');
insert into engine_countries (`name`) values ('Uruguay');
insert into engine_countries (`name`) values ('Venezuela');
insert into engine_countries (`name`) values ('Vietnam');
