/*
ts:2016-04-27 16:10:00
*/
INSERT IGNORE INTO `engine_counties` (`name`, `region`, `date_created`, `date_modified`, `publish`, `deleted`) VALUES
('Dublin 1',  '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 2',  '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 3',  '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 4',  '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 5',  '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 6',  '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 7',  '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 8',  '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 9',  '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 10', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 11', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 12', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 13', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 14', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 15', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 16', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 17', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 18', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 19', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 20', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 21', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 22', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 23', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0'),
('Dublin 24', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', '0');
