/*
ts:2015-11-25 00:00:00
engine.plugin.media:20151125000000
*/
-- IBCMS-729
ALTER TABLE `shared_media` RENAME TO `plugin_media_shared_media`;
ALTER TABLE `shared_media_photo_presets` RENAME TO `plugin_media_shared_media_photo_presets`;
CREATE OR REPLACE VIEW `pmedia_view_media_presets_list_admin` AS select `plugin_media_shared_media_photo_presets`.`id` AS `id`,`plugin_media_shared_media_photo_presets`.`title` AS `title`,`plugin_media_shared_media_photo_presets`.`directory` AS `directory`,`plugin_media_shared_media_photo_presets`.`height_large` AS `height_large`,`plugin_media_shared_media_photo_presets`.`width_large` AS `width_large`,`plugin_media_shared_media_photo_presets`.`action_large` AS `action_large`,`plugin_media_shared_media_photo_presets`.`thumb` AS `thumb`,`plugin_media_shared_media_photo_presets`.`height_thumb` AS `height_thumb`,`plugin_media_shared_media_photo_presets`.`width_thumb` AS `width_thumb`,`plugin_media_shared_media_photo_presets`.`action_thumb` AS `action_thumb`,`plugin_media_shared_media_photo_presets`.`date_created` AS `date_created`,`plugin_media_shared_media_photo_presets`.`created_by` AS `created_by`,`users_create`.`name` AS `created_by_name`,`roles_create`.`role` AS `created_by_role`,`plugin_media_shared_media_photo_presets`.`date_modified` AS `date_modified`,`plugin_media_shared_media_photo_presets`.`modified_by` AS `modified_by`,`users_modify`.`name` AS `modified_by_name`,`roles_modify`.`role` AS `modified_by_role`,`plugin_media_shared_media_photo_presets`.`publish` AS `publish` from ((((`plugin_media_shared_media_photo_presets` left join `users` `users_create` on((`plugin_media_shared_media_photo_presets`.`created_by` = `users_create`.`id`))) left join `users` `users_modify` on((`plugin_media_shared_media_photo_presets`.`modified_by` = `users_modify`.`id`))) left join `engine_project_role` `roles_modify` on((`users_modify`.`role_id` = `roles_modify`.`id`))) left join `engine_project_role` `roles_create` on((`users_create`.`role_id` = `roles_create`.`id`))) where (`plugin_media_shared_media_photo_presets`.`deleted` = 0);

INSERT IGNORE INTO `settings` (`variable`, `name`, `linked_plugin_name`, `value_live`, `value_stage`, `value_test`, `value_dev`, `default`, `note`, `type`, `group`, `options`)
VALUES ('show_submenu_in_sidebar', 'Submenus in the Sidebar', 'menus', '0', '0', '0', '0', '0', 'If a page is in a submenu of main menu, display it and its siblings in the sidebar', 'toggle_button', 'Website', 'Model_Settings,on_or_off');
