/*
ts:2019-01-15 09:33:00
*/

ALTER TABLE plugin_reports_reports ADD COLUMN bulk_messages_per_minute DOUBLE;
INSERT INTO `plugin_reports_reports` (`name`, `sql`, `category`, `sub_category`, `dashboard`, `publish`, `delete`, `report_type`, `checkbox_column`, `action_button_label`, `action_button`, `action_event`, `checkbox_column_label`, `bulk_message_email_column`, `bulk_message_body`, `bulk_messages_per_minute`) VALUES ('Student Interviews', 'select \r\n		students.id as `Student ID`,\r\n		bookings.booking_id as `Interview ID`,\r\n		CONCAT_WS(\' \', students.first_name, students.last_name) as `Student`,\r\n		emails.`value` as `Email`,\r\n		mobiles.`value` as `Mobile`,\r\n		courses.title as `Course`,\r\n		schedules.`name` as `Schedule`,\r\n		timeslots.datetime_start as `Date`,\r\n		applications.interview_status as `Status`\r\n		\r\n	from plugin_ib_educate_bookings bookings\r\n		inner join plugin_ib_educate_bookings_has_courses has_courses on bookings.booking_id = has_courses.booking_id and has_courses.deleted = 0\r\n		inner join plugin_courses_courses courses on has_courses.course_id = courses.id\r\n		inner join plugin_ib_educate_bookings_has_applications applications on bookings.booking_id = applications.booking_id\r\n		inner join plugin_ib_educate_booking_items items on bookings.booking_id = items.booking_id and items.`delete` = 0\r\n		inner join plugin_courses_schedules_events timeslots on items.period_id = timeslots.id\r\n		inner join plugin_courses_schedules schedules on timeslots.schedule_id = schedules.id\r\n		inner join plugin_contacts3_contacts students on bookings.contact_id = students.id\r\n		left join plugin_contacts3_contact_has_notifications emails on students.notifications_group_id = emails.group_id and emails.notification_id=2\r\n		left join plugin_contacts3_contact_has_notifications mobiles on students.notifications_group_id = mobiles.group_id and mobiles.notification_id=1\r\n	where bookings.`delete` = 0 and bookings.booking_status <> 3 and applications.interview_status is not null\r\n	order by `Student`', '0', '0', '0', '1', '0', 'sql', '1', 'Send Emails', '1', 'var students = [];\r\n$(\"#report_table tbody .row_check:checked\").each(function(){\r\n	var $td = $(this).parents(\"tr\").find(\"td\");\r\n	var student = {};\r\n	student[\"Student ID\"] = $td[0].innerHTML;\r\n	student[\"Interview ID\"] = $td[1].innerHTML;\r\n	student[\"Student\"] = $td[2].innerHTML;\r\n	student[\"Email\"] = $td[3].innerHTML;\r\n	student[\"Mobile\"] = $td[4].innerHTML;\r\n	student[\"Course\"] = $td[5].innerHTML;\r\n	student[\"Schedule\"] = $td[6].innerHTML;\r\n	student[\"Date\"] = $td[7].innerHTML;\r\n	student[\"Status\"] = $td[8].innerHTML;\r\n	students.push(student);\r\n});\r\n$.post(\r\n	\"/admin/reports/send_report\",\r\n	{\r\n		id: $(\"#id\").val(),\r\n		data: students\r\n	},\r\n	function (response) {\r\n		alert(\"Send complete\");\r\n	}\r\n);', 'Select', 'Email', 'Hello {Student}\r\nYou have an interview for {Course} on {Date}\r\n', '10');

INSERT INTO `plugin_reports_parameters`
  (`report_id`, `type`, `name`, `value`, `is_multiselect`)
  VALUES
  ((select id from plugin_reports_reports where name = 'Student Interviews' and `delete`=0 limit 1), 'custom', 'course', 'select id, CONCAT_WS(\' - \' , `code`, title) as course from plugin_courses_courses where deleted=0 order by code', '0');

UPDATE `plugin_reports_reports`
  SET
    `sql`='select \r\n		students.id as `Student ID`,\r\n		bookings.booking_id as `Interview ID`,\r\n		CONCAT_WS(\' \', students.first_name, students.last_name) as `Student`,\r\n		emails.`value` as `Email`,\r\n		mobiles.`value` as `Mobile`,\r\n		courses.title as `Course`,\r\n		schedules.`name` as `Schedule`,\r\n		timeslots.datetime_start as `Date`,\r\n		applications.interview_status as `Status`\r\n		\r\n	from plugin_ib_educate_bookings bookings\r\n		inner join plugin_ib_educate_bookings_has_courses has_courses on bookings.booking_id = has_courses.booking_id and has_courses.deleted = 0\r\n		inner join plugin_courses_courses courses on has_courses.course_id = courses.id\r\n		inner join plugin_ib_educate_bookings_has_applications applications on bookings.booking_id = applications.booking_id\r\n		inner join plugin_ib_educate_booking_items items on bookings.booking_id = items.booking_id and items.`delete` = 0\r\n		inner join plugin_courses_schedules_events timeslots on items.period_id = timeslots.id\r\n		inner join plugin_courses_schedules schedules on timeslots.schedule_id = schedules.id\r\n		inner join plugin_contacts3_contacts students on bookings.contact_id = students.id\r\n		left join plugin_contacts3_contact_has_notifications emails on students.notifications_group_id = emails.group_id and emails.notification_id=2\r\n		left join plugin_contacts3_contact_has_notifications mobiles on students.notifications_group_id = mobiles.group_id and mobiles.notification_id=1\r\n	where bookings.`delete` = 0 and bookings.booking_status <> 3 and applications.interview_status is not null and (courses.id = \"{!course!}\" or \'\' = \"{!course!}\")\r\n	order by `Student`'
  WHERE (name = 'Student Interviews');
