/*
ts:2015-01-01 00:01:02
*/

-- ---------------------------------------------------
-- GP-24 Improvement: Add date and time field (popup calendar)
-- ---------------------------------------------------
UPDATE IGNORE `plugin_formbuilder_forms` SET `fields` = '<input type="hidden" name="redirect" value="thank-you.html" id="redirect"><input type="hidden" name="trigger" value="custom_form" id="trigger"><input type="hidden" name="email_template" id="email_template" value="quick_order"><input type="hidden" name="form_identifier" id="form_identifier" value=""><input type="hidden" name="event" value="remindme" id="event"><li><fieldset id="Customer Details"><legend>Customer Details</legend><ul><li><label>Your Name:</label><input type="text" name="name" id="name"></li><li><label>Telephone No.</label><input type="text" name="telephone" id="telephone"></li><li><label for="address">Address</label><textarea name="address" id="address" cols="" rows="4"></textarea></li><li><label>Email</label><input type="text" name="email" id="email"></li><li><label>Budget &euro;</label><input type="text" name="budget" id="budget"></li><li><label for="quick_order_delivery_date">Delivery Date</label><input type="text" class="datepicker" name="delivery_date" id="quick_order_delivery_date"></li><li><label for="quick_order_delivery_time">Delivery Time</label><input type="text" name="delivery_time" id="quick_order_delivery_time" class="timepicker"></li><li><label>Type of Event</label><input type="text" name="event_type" id="event_type"></li></ul></fieldset></li>                <li><fieldset id="Recipient Details"><legend>Recipient Details</legend><ul><li><label for="recipient_name">Recipient Name</label><input type="text" name="recipient_name" id="recipient_name"></li><li><label for="recipient_address">Recipient Address</label><textarea name="recipient_address" id="recipient_address" rows="4"></textarea></li><li><label for="recipient_phone">Recipient Phone </label><input type="text" name="recipient_phone" id="recipient_phone"></li><li><label for="recipient_email">Recipient Email</label><input type="text" name="recipient_email" id="recipient_email"></li></ul></fieldset></li><li><label for="comments">Comments</label><textarea name="comments" id="comments" rows="4"></textarea></li>                <li><label for="place_order"></label><button name="Place Order" value="Place Order" id="place_order">Place Order</button></li>'
WHERE `form_name` = 'Quick_Order_Form';

UPDATE IGNORE `plugin_formbuilder_forms` SET `fields` = '<input type="hidden" name="redirect" value="thank-you.html" id="redirect"><input type="hidden" name="trigger" value="custom_form" id="trigger"><input type="hidden" name="email_template" id="email_template" value="quick_order"><input type="hidden" name="form_identifier" id="form_identifier" value=""><input type="hidden" name="event" value="quick_order" id="event"><li><fieldset id="Customer Details"><legend>Customer Details</legend><ul><li><label>Your Name:</label><input type="text" name="name" id="name"></li><li><label>Telephone No.</label><input type="text" name="telephone" id="telephone"></li><li><label for="address">Address</label><textarea name="address" id="address" cols="" rows="4"></textarea></li><li><label>Email</label><input type="text" name="email" id="email"></li><li><label>Budget &euro;</label><input type="text" name="budget" id="budget"></li><li><label for="quick_order_delivery_date">Delivery Date</label><input type="text" class="datepicker" name="delivery_date" id="quick_order_delivery_date"></li><li><label for="quick_order_delivery_time">Delivery Time</label><input type="text" name="delivery_time" id="quick_order_delivery_time" class="timepicker"></li><li><label>Type of Event</label><input type="text" name="event_type" id="event_type"></li></ul></fieldset></li>                <li><fieldset id="Recipient Details"><legend>Recipient Details</legend><ul><li><label for="recipient_name">Recipient Name</label><input type="text" name="recipient_name" id="recipient_name"></li><li><label for="recipient_address">Recipient Address</label><textarea name="recipient_address" id="recipient_address" rows="4"></textarea></li><li><label for="recipient_phone">Recipient Phone </label><input type="text" name="recipient_phone" id="recipient_phone"></li><li><label for="recipient_email">Recipient Email</label><input type="text" name="recipient_email" id="recipient_email"></li></ul></fieldset></li><li><label for="comments">Comments</label><textarea name="comments" id="comments" rows="4"></textarea></li>                <li><label for="place_order"></label><button name="Place Order" value="Place Order" id="place_order">Place Order</button></li>'
WHERE `form_name` = 'Quick_Order_Form';

INSERT IGNORE INTO `plugin_notifications_event` (`name`, `description`, `subject`) VALUES ('quick_order', 'Quick Order', 'Quick Order');

UPDATE IGNORE `plugin_formbuilder_forms` SET `fields`='<input type=\"hidden\" name=\"redirect\" value=\"thank-you.html\" id=\"redirect\"><input type=\"hidden\" name=\"trigger\" value=\"custom_form\" id=\"trigger\"><input type=\"hidden\" name=\"email_template\" id=\"email_template\" value=\"quick_order\"><input type=\"hidden\" name=\"form_identifier\" id=\"form_identifier\" value=\"\"><input type=\"hidden\" name=\"event\" value=\"quick_order\" id=\"event\"><li><fieldset id=\"Customer Details\"><legend>Customer Details</legend><ul><li><label>Your Name:</label><input type=\"text\" name=\"name\" id=\"name\"></li><li><label>Telephone No.</label><input type=\"text\" name=\"telephone\" id=\"telephone\"></li><li><label for=\"address\">Address</label><textarea name=\"address\" id=\"address\" cols=\"\" rows=\"4\"></textarea></li><li><label>Email</label><input type=\"text\" name=\"email\" id=\"email\"></li><li><label>Budget &euro;</label><input type=\"text\" name=\"budget\" id=\"budget\"></li><li><label for=\"quick_order_delivery_time\">Delivery Time</label><input type=\"text\" name=\"delivery_time\" id=\"quick_order_delivery_time\" class=\"datetimepicker\"></li><li><label>Type of Event</label><input type=\"text\" name=\"event_type\" id=\"event_type\"></li></ul></fieldset></li>                <li><fieldset id=\"Recipient Details\"><legend>Recipient Details</legend><ul><li><label for=\"recipient_name\">Recipient Name</label><input type=\"text\" name=\"recipient_name\" id=\"recipient_name\"></li><li><label for=\"recipient_address\">Recipient Address</label><textarea name=\"recipient_address\" id=\"recipient_address\" rows=\"4\"></textarea></li><li><label for=\"recipient_phone\">Recipient Phone </label><input type=\"text\" name=\"recipient_phone\" id=\"recipient_phone\"></li><li><label for=\"recipient_email\">Recipient Email</label><input type=\"text\" name=\"recipient_email\" id=\"recipient_email\"></li></ul></fieldset></li><li><label for=\"comments\">Comments</label><textarea name=\"comments\" id=\"comments\" rows=\"4\"></textarea></li>                <li><label for=\"place_order\"></label><button name=\"Place Order\" value=\"Place Order\" id=\"place_order\">Place Order</button></li>'
WHERE `form_name` = 'Quick_Order_Form';

